In [1]:
!pip -q install datasets pandas tqdm

import os
import re
import pandas as pd

from datasets import load_dataset
from tqdm.auto import tqdm

OUTPUT_FILE = "writing.csv"

if not os.path.exists(OUTPUT_FILE):
    pd.DataFrame(columns=["prompt", "response"]).to_csv(OUTPUT_FILE, index=False)

In [7]:
import os
import re
import html
import random
import pandas as pd

from tqdm.auto import tqdm
from datasets import load_dataset
from tokenizers import Tokenizer

random.seed(42)

tokenizer = Tokenizer.from_file(
    "/kaggle/input/datasets/punitkashyap2007/virgo-tokenizer/virgo_tokenizer.json"
)

OUTPUT_FILE = "writing.csv"

if os.path.exists(OUTPUT_FILE):
    writing_df = pd.read_csv(OUTPUT_FILE)
else:
    writing_df = pd.DataFrame(columns=["prompt", "response"])

existing_pairs = set(
    zip(
        writing_df["prompt"].astype(str),
        writing_df["response"].astype(str)
    )
)

rows = []

In [8]:
def clean_text(text):
    if text is None:
        return ""

    text = html.unescape(str(text))
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [9]:
def token_count(text):
    return len(tokenizer.encode(text).ids)

In [10]:
def add_sample(prompt, response):
    prompt = clean_text(prompt)
    response = clean_text(response)

    if not prompt or not response:
        return

    if len(prompt.split()) < 4:
        return

    if len(response.split()) < 3:
        return

    total_tokens = token_count(prompt) + token_count(response)

    if total_tokens > 1024:
        return

    pair = (prompt, response)

    if pair in existing_pairs:
        return

    existing_pairs.add(pair)

    rows.append({
        "prompt": prompt,
        "response": response
    })

In [11]:
dataset = load_dataset(
    "EdinburghNLP/xsum",
    split="train"
)

In [12]:
summary_prompts = [
    "Summarize the following article.",
    "Write a concise summary.",
    "Summarize this passage.",
    "Summarize the article below.",
    "Provide a brief overview.",
    "Explain the article briefly.",
    "Capture the key points.",
    "Write a short abstract.",
    "Summarize the main ideas.",
    "What is this article about?",
    "Reduce this article to its essential points.",
    "Extract the important information.",
    "Provide a compact summary.",
    "Describe the article in a few sentences.",
    "Write a clear summary.",
    "Give the gist of the following article.",
    "Summarize the content below.",
    "Briefly describe the following article.",
    "Generate a summary.",
    "Summarize this document."
]

In [13]:
for sample in tqdm(dataset):

    document = clean_text(sample["document"])
    summary = clean_text(sample["summary"])

    if len(document.split()) < 80:
        continue

    prompt = f"{random.choice(summary_prompts)}\n\n{document}"

    add_sample(prompt, summary)

print(len(rows))

  0%|          | 0/204045 [00:00<?, ?it/s]

169005

In [14]:
preview = pd.DataFrame(rows)

preview.sample(
    min(10, len(preview)),
    random_state=42
)[["prompt", "response"]]

,prompt,response
146344,"Summarize the following article. Widely regarded as the third tier of the sport, after the NFL and college leagues, some matches are televised at prime time on Friday nights. But one school from Washington is struggling to get on the pitch, with three successive opponents forfeiting matches against them. The Wildcats from Archbishop Murphy High School (AMHS) won their first three matches this year by a combined score of 170-0. But their next three opponents - South Whidbey, Sultan and Granite Falls - have all refused to face them. AMHS have six players weighing at least 17 stone, including three at more than 21st, and are so dominant staff and parents from other schools are becoming increasingly concerned about player safety. A private Catholic school, AMHS is able to recruit students from a wider catchment area than the local comprehensive schools. ""The level of athletes they've been able to bring in on one team doesn't match up with a lot of the teams in our league,"" said Tim Dennis, head coach of Granite Falls. ""It's not that we're afraid to play the game, it's an injury issue."" During a tense meeting of parents, players and officials, the mother of one Granite Falls player said: ""My 14-year-old son is 5ft 8in and weighs 117 pounds (8st 5lbs). They've got 18-year-old players that are 6ft 5in and weigh 330 pounds (23st 5lbs). ""That's like putting a Volkswagen Bug against a truck."" But AMHS head coach Jerry Jensen said forfeiting matches did not ""ring true"" to what schools should be teaching their pupils. ""This is their opportunity to face adversity, power through it, and it will serve them well in their life,"" he said. AMHS play in the Cascade Conference, but there are growing calls for them to play in a higher division.","In some parts of the United States, high school American football is a huge deal."
38367,"What is this article about? It was the warmest December since records began in 1910 - and the wettest of any calendar month on record. Mean temperatures were about 4C (7.2F) above the long-term average. The Met Office says there is a direct link between the warmth and the record rains that brought widespread floods across Scotland, Northern Ireland and northern England. Stormy December 'was wettest on record' Storms propelled by the jet stream were mainly to blame, it says, with contributions from the El Nino weather phenomenon and man-made climate change. December was something of a freak month, it acknowledges. It says climate change has raised UK temperatures by around 1C (1.8F) so far, so it will be many decades before this level of extreme weather becomes the new winter norm. Other scientists say that with climate change, there will be no ""normal"" weather. Meanwhile, the unseasonal warmth has disrupted the natural world, and affected the way we live and the amount of cash we have to spend. People in T-shirts have been out in the gloom of winter, fuel bills are down, and the winter deaths total is likely to be lower than usual. Plants are also flowering at bizarre times. In Kew Gardens, in south-west London, a magnolia tree is in full bloom alongside daffodils. A currant bush - Ribes sanguineum - came into flower before Christmas when it is normally expected in March. My own garden in London still has a rose in flower and a strawberry on its bush. Tony Kirkham, head of the arboretum at Kew Gardens, said the recent jumbling of seasons was causing problems in the natural world. ""The plants are really mixed up, they don't know what season they're in. They think spring is on the way, and they need to flower and grow leaves to make food. ""The seasons are normally quite short so they do it as soon as time allows. ""The downside is is that we could get a frost, and all these young leaves are very tender and not used to temperatures below freezing, and they won't flower again in spring. ""And it's a food source for insects that won't be around when insects need it."" The Met Office does not expect the exceptional warmth to continue. We will be heading for colder, drier weather in late winter, it says - although it is loath to offer a hostage to fortune by predicting exactly when. Prof Adam Scaife, head of medium-term prediction at the Met Office, said: ""The mild, wet weather is coming to an end - not this week but in a while. ""This December has really been out of the ordinary. We think climate change has played a part in the extreme temperature and rainfall - but only a minor one. ""It's not feasible for climate change to have increased temperatures as high as they have been - the jet stream has been the main driver of conditions, bringing winter storms. ""Warmer air can hold more moisture, and we expect winters to become warmer and wetter with climate change - especially in the North. But we wouldn't expect the sort of weather we've had in December to become normal in the UK for many decades."" Prof Myles Allen, from Oxford's department of atmospheric physics, said this was too cautious. ""There is no such thing as a new normal with climate change,"" he said. ""Climate change is not a transition to a new normal. It's a trend. Decembers like this will be what we expect in a couple of decades' time."" Follow Roger Harrabin on Twitter: @rogerharrabin; and on Facebook.","A wet, but mild, December was a record-breaking month, the UK Met Office's final figures show - so why was it so extreme and can we expect more of the same?"
130622,"Summarize the following article. Turia Pitt received burns to 65% of her body and was told she would never compete again after the 2011 ultra-marathon in the Kimberley region. But on Sunday she completed the 226km (140 mile) Ironman Australia triathlon, making headlines across the country. Ms Pitt told the BBC she never doubted that she would cross the finish line. ""I kind of just got in my zone and didn't really think about the big picture, I just broke it down into little chunks, I just thought about getting to the next station,"" the 28-year-old said of the triathlon, which was held at Port Macquarie, 390km (242 miles) north of Sydney. ""I was confident I'd get to the end unless I had really bad luck, like [if] I came off my bike, but those kinds of things aren't really in my control"". Ms Pitt spent 864 days in hospital and underwent more than 100 surgeries to treat her injuries after the 2011 race. Hong Kong-based Racing the Planet, which organised the event, had not put in place proper procedures to prevent injury in the event of a bushfire, an inquiry later found. A total of five competitors suffered severe burns. Ms Pitt, now an author and motivational speaker, used the race on Sunday to raise money for Interplast. The agency provides free reconstructive surgery to people in developing countries in the Asia Pacific.",An Australian runner who suffered life-threatening burns when she was caught in a bushfire during a race has finished a gruelling Ironman triathlon.
3493,"Summarize this document. Yoan Gouffran gave the visitors the lead when he thundered in a volley from Jonjo Shelvey's corner. Craig Bryson had the Rams' best chance after the break, but his powerful shot from the edge of the box was parried away by goalkeeper Matz Sels. The Magpies sealed the win in injury time, Ayoze Perez finding DeAndre Yedlin to scuff a shot home. Derby's goal-scoring difficulties continue, having scored just once in their first six league games despite handing debuts to an attacking trio of Matej Vydra, James Wilson and Ikechi Anya, who were signed before the transfer window closed. By contrast, Rafael Benitez's Newcastle have now recovered from their wobbly start to the campaign to pick up four straight wins in the second tier, with keeper Sels barely tested. That was in no small part down to the defensive effort throughout the side, typified by wingers Matt Ritchie and Gouffran doubling up with their full-backs to deny Derby the opportunity to bring their attacking additions into the game. They were also ruthless enough to take their chances, soaking up Derby's second-half resurgence and then releasing the pressure with a late sucker-punch second goal. Match ends, Derby County 0, Newcastle United 2. Second Half ends, Derby County 0, Newcastle United 2. Goal! Derby County 0, Newcastle United 2. DeAndre Yedlin (Newcastle United) left footed shot from very close range to the centre of the goal following a corner. Corner, Newcastle United. Conceded by Will Hughes. Corner, Newcastle United. Conceded by Johnny Russell. Foul by Darren Bent (Derby County). Isaac Hayden (Newcastle United) wins a free kick in the defensive half. Substitution, Derby County. Darren Bent replaces Jason Shackell. Substitution, Newcastle United. Isaac Hayden replaces Mohamed Diamé. Attempt saved. Mohamed Diamé (Newcastle United) left footed shot from outside the box is saved in the bottom left corner. Attempt blocked. Tom Ince (Derby County) left footed shot from outside the box is blocked. Foul by Will Hughes (Derby County). Matt Ritchie (Newcastle United) wins a free kick on the left wing. Delay over. They are ready to continue. Delay in match Richard Keogh (Derby County) because of an injury. Substitution, Derby County. Tom Ince replaces Ikechi Anya because of an injury. Delay over. They are ready to continue. Delay in match Ikechi Anya (Derby County) because of an injury. Attempt saved. Nick Blackman (Derby County) header from the centre of the box is saved in the bottom right corner. Assisted by Ikechi Anya with a cross. Substitution, Newcastle United. Ayoze Pérez replaces Dwight Gayle. Dwight Gayle (Newcastle United) is shown the yellow card for a bad foul. Richard Keogh (Derby County) wins a free kick in the attacking half. Foul by Dwight Gayle (Newcastle United). Attempt missed. Nick Blackman (Derby County) right footed shot from outside the box misses to the right. Assisted by Matej Vydra with a headed pass. Substitution, Newcastle United. DeAndre Yedlin replaces Yoan Gouffran. Foul by Jack Colback (Newcastle United). Will Hughes (Derby County) wins a free kick in the attacking half. Attempt saved. Craig Bryson (Derby County) right footed shot from outside the box is saved in the centre of the goal. Assisted by Matej Vydra. Foul by Yoan Gouffran (Newcastle United). Cyrus Christie (Derby County) wins a free kick in the defensive half. Substitution, Derby County. Nick Blackman replaces James Wilson. Corner, Derby County. Conceded by Jack Colback. Matt Ritchie (Newcastle United) wins a free kick on the right wing. Foul by Craig Bryson (Derby County). Offside, Derby County. Will Hughes tries a through ball, but Richard Keogh is caught offside. Yoan Gouffran (Newcastle United) is shown the yellow card. Foul by Yoan Gouffran (Newcastle United). Cyrus Christie (Derby County) wins a free kick in the attacking half. Attempt missed. Mohamed Diamé (Newcastle United) right footed shot from outside the box misses to the left. Assisted by Dwight Gayle. Jason Shackell (Derby County) wins a free kick in the defensive half.",Newcastle United moved up to second in the Championship table with a comfortable victory at Derby County.
25514,"Summarize the main ideas. The shooting of Lavontay White and a 26-year-old man were captured on Facebook Live by the woman who was also injured in Tuesday's attack. Police say White and his uncle were shot in the head while riding in a car with his uncle's girlfriend. The shooting is the latest in a wave of gun violence that has gripped the city. Authorities are yet to identify the man, a known gang member who appeared to be the intended target, and his girlfriend. Lavontay White, identified by the Cook County Medical Examiner's office, was later pronounced dead in hospital. The woman and her unborn baby were both listed in fair condition at Mount Sinai Hospital. The chilling footage purported to show the three victims in a car when another vehicle pulled up and a gunman got out and opened fire, according to officials. No arrests have been made but investigators have ""very optimistic leads"", according to police spokesman Anthony Guglielmi. Authorities were also reviewing the footage. The killings come on the heels of the shooting of two girls, ages 11 and 12, who were both hit in separate incidents that took place less than 30 minutes of each other on Chicago's South Side on Saturday. Two girls shot in head in Chicago Takiya Holmes, 11, was sitting in her family's minivan when she was shot in the head. Less than an hour later, Kanari Gentry-Bowers, 12, was also struck in the head while playing basketball at her primary school's playground. Holmes was pronounced dead on Tuesday while Gentry-Bowers remains in a critical condition. Chicago has seen a spike in gang-related violence that has garnered national attention from both media and President Donald Trump. The city had 4,000 shooting victims and 762 homicides last year, according to police statistics. The violence has continued this year, with at least 76 homicides reported so far in 2017. Mayor Rahm Emanuel released a statement on Tuesday ,saying that when children are caught in the crossfire, ""our consciences are shaken and our hearts are broken"".","A two-year-old boy and his uncle were killed, and a pregnant woman was wounded in a suspected gang shooting on Chicago's West Side, police said."
5827,"Summarize this passage. The men were arrested across south Birmingham and at an address in Liverpool, West Midlands Police said. They have been charged with conspiracy to supply class A drugs and are due before Birmingham magistrates later. The raids are part of an operation between police and the Prison Service targeting the supply of cocaine between organised crime groups in the cities. Eight other people were arrested across south Birmingham last week in connection with the operation, the force said. Three women and four men were charged with conspiracy to supply class A drugs and will appear at the same court on Thursday 4 June. One man was released on bail pending further enquiries. Officers recovered large amounts of cash, cannabis and various weapons from the addresses, a spokesman said.",Four people have been charged by police investigating an alleged drugs ring in Liverpool and Birmingham.
123519,"Summarize this passage. The public should mobilise against Israel so that it ""does pay a price for the position that it is taking"", Mr Mbeki said in the capital, Pretoria. About 2,000 people, mostly Palestinians, have died in the conflict in Gaza since July. Most South Africans have historically supported the Palestinians. BBC South Africa analyst Farouk Chothia says they include the country's first black president - the late Nelson Mandela - Nobel peace laureate Archbishop Desmond Tutu and prominent Jewish leaders such as Ronnie Kasrils and the late Joe Slovo. They drew parallels between the anti-apartheid struggle in South Africa and the Palestinian campaign for independence, he says. However, South Africa has a vocal minority which supports Israel and believe that it is unfairly maligned. Meanwhile, a row has broken out after the Jewish deputy head boy of Johannesburg's King David Victory Park School, Joshua Broomberg, appeared in a photo posted on Facebook wearing a Palestinian scarf. Hundreds of people signed an online petition demanding that he be stripped of his school honours. Mr Kasrils described the petition as ""disgraceful"", and said Joshua Broomberg was made of ""sterling stuff"", South Africa's privately owned Eyewitness News reports. The schoolboy appeared in a photo with two other students, and a counter petition has been launched to rally support for them, it reports. Mr Mbeki, in an address to students at the University of South Africa, rejected calls for the government to recall its ambassador to Tel Aviv, saying South Africa needed to ""engage"" with Israel to find a ""just solution"" to the conflict. At the same time, South Africa's political parties, trade unions and religious groups should mobilise for a boycott of Israeli goods and ""divesting"" from Israeli companies, he said. ""It is not the responsibility of government to mobilise people. We must mobilise ourselves.""",South Africa's ex-President Thabo Mbeki has called for a boycott of Israeli goods to show solidarity with Palestinians.
126255,"Write a concise summary. Caroline Glachan, 14, was found dead on the banks of the River Leven in Dunbartonshire on 25 August 1996. The killer has never been found. Her mother, Margaret McKeich, will feature on the Crimewatch appeal, which is due to be broadcast on Monday night. Det Supt Jim Kerr will be in the studio in a bid to generate fresh leads. Last week, the detective appeared at a news conference with Mrs McKeich and Caroline's friend, Joanne Menzies, who was one of the last people to have seen her alive. In a clip released by the BBC ahead of the Crimewatch broadcast, Mrs McKeich said: ""I looked out the window and there was a police officer with a police woman and I knew. I just knew. I got this unbelievable pain, which I can still feel, just a pain in my heart. I just knew it was her. ""They came up and they asked about her and the clothing that she had on. I told them and they said that they believed that it was her but they would have to identify her. ""Of course by this time it is my birthday so life didn't begin at 40. For me, it basically ended."" Mrs McKeich, 60, said she believes locals know who is responsible for her daughter's death and appealed for them to contact detectives. She said: ""I would urge anybody to come forward, just to give me that peace and to give me closure. ""There's two questions I need answered - who and why."" Caroline, from Bonhill, was heading to meet her boyfriend in Renton, having spent an evening with friends, and took a short cut from shops along Dillichip Loan towards The Towpath and the Black Bridge. On the Crimewatch programme, her friend Ms Menzies returned to the area where they parted for the final time. Urging those with information to come forward, she said: ""Caroline was only a child, she was only 14. ""These people should now stand up and actually finally be counted as a human being and not hiding a sickening secret."" Police Scotland's Homicide Governance and Review team have begun a fresh investigation and forensic scientists are re-examining more than 300 items collected at the time of Caroline's death. Speaking at last week's press conference, Det Supt Jim Kerr appealed to the local community to break the ""wall of silence"" surrounding Caroline's murder. He also urged a man in a hooded top, who was seen near where Caroline's body was found, to come forward. ""There's people in this community that know exactly happened. I feel as if it's a black cloud over Renton and Bonhill and we need to get it lifted,"" he said.",The mother of a schoolgirl who was murdered 20 years ago is to appeal for help in finding her daughter's killer on the BBC's Crimewatch programme.

In [15]:
df = pd.DataFrame(rows)

if len(df) > 8000:
    df = df.sample(
        n=8000,
        random_state=42
    ).reset_index(drop=True)

if os.path.exists(OUTPUT_FILE):

    old = pd.read_csv(OUTPUT_FILE)

    df = (
        pd.concat([old, df], ignore_index=True)
          .drop_duplicates(subset=["prompt", "response"])
          .reset_index(drop=True)
    )

df.to_csv(OUTPUT_FILE, index=False)

print(df.shape)

(16000, 2)

In [16]:
dataset = load_dataset(
    "abisee/cnn_dailymail",
    "3.0.0",
    split="train"
)

README.md: 0.00B [00:00, ?B/s]

3.0.0/train-00000-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00001-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00002-of-00003.parquet:   0%|          | 0.00/259M [00:00<?, ?B/s]

3.0.0/validation-00000-of-00001.parquet:   0%|          | 0.00/34.7M [00:00<?, ?B/s]

3.0.0/test-00000-of-00001.parquet:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

In [17]:
summary_prompts = [
    "Summarize the following article.",
    "Write a concise summary of the article below.",
    "Provide a brief overview of the following news article.",
    "Summarize the main points.",
    "Write an abstract for the article.",
    "Condense the following article.",
    "Explain the article briefly.",
    "Capture the key ideas.",
    "Write a short summary.",
    "Summarize this document.",
    "What is this article about?",
    "Describe the article in a few sentences.",
    "Reduce this article to its essential points.",
    "Extract the important information.",
    "Provide a compact summary.",
    "Generate a brief summary.",
    "Write a news summary.",
    "Summarize the content below.",
    "Identify the main takeaway from the article.",
    "Summarize this text clearly."
]

start = len(rows)

for sample in tqdm(dataset):

    article = clean_text(sample["article"])
    summary = clean_text(sample["highlights"])

    if len(article.split()) < 80:
        continue

    prompt = f"{random.choice(summary_prompts)}\n\n{article}"

    add_sample(prompt, summary)

added = len(rows) - start

print(f"Added: {added:,}")

  0%|          | 0/287113 [00:00<?, ?it/s]

Added: 183,081

In [18]:
preview = pd.DataFrame(rows)

print(f"Current Samples: {len(preview):,}")

samples = preview.sample(min(10, len(preview)), random_state=42).reset_index(drop=True)

for i, row in samples.iterrows():
    print("=" * 120)
    print(f"Sample {i+1}")
    print("-" * 120)
    print("Prompt:")
    print(row["prompt"])
    print()
    print("Response:")
    print(row["response"])
    print()

Current Samples: 352,086
========================================================================================================================
Sample 1
------------------------------------------------------------------------------------------------------------------------
Prompt:
Provide a brief overview. Warm temperatures are being experienced widely across Scotland, but so far they are still below the Scottish May record of 30.9C of five years ago. By 14:00, the temperature was 27.2C in Aboyne in Aberdeenshire, 25C in Inverness and Aviemore in the Highlands and 24C in Edinburgh and Glasgow. High temperatures have also been forecast for Friday when it could reach 29C. The top May temperature was recorded in Inverailort in the Highlands. BBC Scotland Weather said 27-28C was likely to be the hottest on Thursday, with the average expected to be between 13 and 16C. Warm and dry weather has been a feature of May this year. The previous month in Scotland was largely cold and wet with some snowfall. May is traditionally seen as one of the best months for long spells of fine weather in Scotland.

Response:
All pictures via the BBC's Weather Watchers.

========================================================================================================================
Sample 2
------------------------------------------------------------------------------------------------------------------------
Prompt:
Reduce this article to its essential points. Sandra Avila Beltran, known as the "Queen of the Pacific" for alleged drug dealings, was deported Tuesday from the United States to Mexico, where she will face money-laundering charges, the third set of criminal accusations against her. Avila landed in Mexico City on a chartered plane from El Paso, Texas, along with other deportees, the Mexican attorney general's office said. She was being held in a hangar belonging to the attorney general's office, where she will be served with an arrest warrant, the state-run Notimex news agency reported. She will undergo a medical exam before being transported to the state of Jalisco, where she faces charges of money laundering, according to Notimex. Avila's name stands out on the list of accused leaders of Mexico's male-dominated drug trade. The 52-year-old's life is the subject of a best-selling book and a popular ballad. She was dubbed Queen of the Pacific because the smuggling routes she is alleged to have controlled brought drugs from Colombia to Mexico along the Pacific Coast. Avila's lawyer, Stephen Ralls, told CNNMexico last week that Avila is "optimistic" about facing what will be her third judicial process, after being exonerated in her first trial in Mexico and having reach a plea deal in her second case in the United States. Mexico arrests alleged leader of Gulf Cartel . A federal court in Miami in July sentenced Avila to 70 months in prison for helping a Colombian drug lord, but under the plea deal the judge ruled that her time served in Mexico and in the United States was enough to complete her sentence. The judge ordered her deportation. Avila was first arrested in Mexico City on September 28, 2007, smiling before cameras as authorities trumpeted her detention. Mexico's case against her drew widespread attention as it made its way through the nation's courts. After her acquittal, authorities extradited her last year to the United States, where she was accused of conspiring to smuggle cocaine along with Juan Diego Espinosa Ramirez, a Colombian national who was also known as "The Tiger." Avila denied the charges. And despite the high-profile accusations against her, authorities have not convicted Avila of any direct drug-trafficking crimes. The U.S. conviction was for being an accessory after the fact.

Response:
Sandra Avila Beltran had pleaded guilty in a drug case in the United States . The judge sentenced her to time served; she is now back in Mexican custody . She faces charges of money laundering in Mexico .

========================================================================================================================
Sample 3
------------------------------------------------------------------------------------------------------------------------
Prompt:
Reduce this article to its essential points. The president made the remarks during a speech in London, after holding talks with Prime Minister David Cameron. Burma, also known as Myanmar, has freed hundreds of political detainees since Thein Sein took power in March 2010. Up until then, it barely acknowledged the prisoners' existence. Their release is part of ongoing political reforms. "By the end of the year there will be no prisoners of conscience in Myanmar," President Thein Sein said on Monday. He added that a special committee was reviewing every political inmate's case. The president is in Britain to discuss trade and military ties. He wants help to boost Burma's economy and Western nations are keen to invest in the resource-rich nation. Earlier, Mr Cameron told the Burmese president greater action was needed on human rights. The British PM said he was "particularly concerned" about the treatment of Rohingya Muslims in Buddhist-majority Burma. Sectarian violence in Rakhine state last year left some 200 people dead and tens of thousands - mostly Rohingya people - displaced. Burmese authorities have been accused of failing to stop the violence and adequately safeguard the rights of Muslims. But the government says Rohingya people are relatively recent migrants from the Indian sub-continent, and so the country's constitution does not include them among indigenous groups qualifying for citizenship. President Thein Sein has introduced major reforms since the elections of November 2010, which saw military rule replaced with a military-backed civilian government. Many political prisoners have been freed and media restrictions have been relaxed. Aung San Suu Kyi's National League for Democracy - which boycotted the November 2010 polls - has rejoined the political process and now has a small presence in parliament. In response, most international sanctions against Burma have been relaxed.

Response:
Burma will release all political prisoners "by the end of the year", President Thein Sein has said during his first official visit to the UK.

========================================================================================================================
Sample 4
------------------------------------------------------------------------------------------------------------------------
Prompt:
What is this article about? The Blues were top of the table from late August and won the title with three games of the season remaining. However, Mourinho, who has led the club to three league titles, says their rivals will improve next season. "We have to be better if we want to be successful again. The other opponents are not going to accept this without a fight," he told Chelsea TV. "Next year will be more difficult, but because it's difficult is one of the reasons why I came back to England. I will enjoy it again." Despite his warning, the Portuguese told Chelsea fans during an open-top bus parade through west London that they should plan for another victory celebration next season. "Thank you for everything, for all your support. Book another place for the parade next season. I hope we can give you that," he said. Second-placed Manchester City and Arsenal, who finished third, are expected to bring in new signings while Manchester United manager Louis van Gaal has been told he can eclipse the £150m he spent last summer. Departing striker Didier Drogba says Chelsea also need to strengthen to challenge in Europe as well as the Premier League next season. "The team needs to be stronger next year to compete in the Champions League," he said. "They are going to buy new players. Also we have young players coming up, the (Dominic) Solankes, (Ruben) Loftus-Cheeks, (Nathan) Akes, all these boys. They need to play." Drogba also wants goalkeeper Petr Cech, who has one year remaining on his Chelsea contract, to stay at the club. Cech's future is uncertain after he lost his place to Thibaut Courtois this season after nearly a decade as Chelsea's first-choice keeper. "No matter what happens I think the club will respect his decision," added Drogba. "If he wants to stay, he can stay. I think he is more than welcome here. If he wants to go it's his choice as well. It's up to him. But we want him to stay."

Response:
Chelsea must improve next season if they are to defend their Premier League title, says boss Jose Mourinho

========================================================================================================================
Sample 5
------------------------------------------------------------------------------------------------------------------------
Prompt:
Summarize the content below. Residents of Morayfield in Queensland are baffled that their neighbourhood has been ranked as the second most liveable suburb in Australia. In a new study, mortgage broker Aussie Home Loans has researched the median house price, block size, capital gain and distance to amenities for 3800 localities. According to the results, the Queensland town of Morayfield, 50km north of Brisbane, is the second most liveable destination in Australia. Morayfield in north-east Australia was ranked second most liveable city in Australia, however locals were sceptical of the study on social media . On the Caboolture Herald's Facebook page, the responses to the ranking were largely sceptical. R Cameron Fowler said: 'Whoever voted obviously didn't visit Morayfield.' Mary Spencer said the ranking was the: 'Best joke I have heard so far this year' Lisa Louise said that while people were being overly harsh, the ranking was inaccurate. 'It's not as bad as people think, but 2nd in the country?!? Definately not!!!' Others posts on the page were more supportive. Mrs Curran said considering the facilities it had, Morayfield was perfect. 'I don't need anything else. We're close to shops, the kids' schools, they're close to sporting facilities. We know the neighbours and they're all friendly' she said. 'I think if you are searching for the stuff you need it's probably in the area.' Dallas McCoist, (left) said she was 'proud that Morayfield has absolutely anything you could want,' while Lisa Louise (right) said it's 'definitely not' the second most liveable city in Australia . Roger Meredith has lived in the area for 28 years and said he liked the 'country atmosphere while still being close to the city'. 'We're five minutes from train stations, schools and the shopping centre. It's close to both coasts, Brisbane and Bribie.' 'We've got a quiet sort of street but and there's a school bus that goes through the area too. I think it's what you make of it,' he said. Dallas McCoist, an 11 year resident, said: 'I'm proud of Morayfield and the fact that it has absolutely anything you could want. Maybe if more people took pride in the suburb they lived in maybe it would be a better environment for all.' The study comes after after an Economist study that revealed Australia is now the most overpriced housing market in the world, when measured against incomes and rents of 23 major economies. The inflation is due to a demand for Australian properties that now exceeded the supply.

Response:
New study from Aussie Home Loans ranks the most liveable suburbs in Australia . The study accounted for the median house price, block size, capital gain and distance to amenities for 3800 localities . Morayfield, north of Brisbane, Australia was ranked second on the list . Locals were sceptical of the study on social media .

========================================================================================================================
Sample 6
------------------------------------------------------------------------------------------------------------------------
Prompt:
Extract the important information. The skeleton was unearthed from a shallow pit at the Vindolanda Roman fort, in Northumberland, two years ago. Dr Trudi Buck, of Durham University, was unable determine whether it was a boy or girl but named it Georgie. It is believed the child, aged about 10 and who was tied up, died from a blow to the head and the body was concealed. Foul play is suspected, because human burials in built-up areas were strictly forbidden in Roman times. When the bones were first discovered, it was thought they were those of a large dog. The pit in the barracks has been dated to the middle of the 3rd Century, when the Fourth Cohort of Gauls formed the garrison. At that time, the dead had to be interred or cremated in cemeteries on the outskirts of towns or barracks, so the concealment of a body in this fashion would have been a criminal act. Dr Buck, a biological anthropologist, said the discovery suggested the young victim was either a child slave or the son or daughter of a soldier serving on Hadrian's Wall - giving more weight to the theory that they took their families with them to Northumberland. Dr Buck said: "I think this is definitely a murder or other unnatural death because of the way the body was deposited. "This is very circumstantial, but possibly it was hit over the head with something because we have very good preservation of the body down to wrist bones that are 1cm in size, but not very much of the head. "Maybe a harsh blow to the head caused a fractured skull." Tests on the child's tooth enamel, carried out for a National Geographic Channel TV programme, showed Georgie grew up in the Mediterranean. "It turns out the child is not from the local area and is not even from Britain," Dr Buck said. "Until the child was at least seven or eight, they have been in southern Europe or even North Africa. "This asks lots of questions about who this child was, how did they get from North Africa to northern Britain in the last two years of their life, and then get killed?" Dr Buck said the Romans' use of child slaves was well-documented, so perhaps that explained how the youngster came to live by Hadrian's Wall. "It is very sad and goes to show human nature does not change," she said. "Perhaps there was an accident and the soldiers tried to hush it up. This is a child who was not given any rituals and Romans were very strict on burial in the right place. "When I was working on it I was very much conscious this was a child and I gave it a name very quickly so I didn't have to keep calling it 'it'."

Response:
A child from 1,800 years ago whose skeleton was found at a fort in north-east England was from the Mediterranean and probably murdered, an expert said.

========================================================================================================================
Sample 7
------------------------------------------------------------------------------------------------------------------------
Prompt:
Summarize the article below. Han Sang-gyun, head of the Korean Confederation of Trade Unions (KCTU), surrendered to police on Thursday He is accused of inciting violence at an anti-government rally on 14 November. On Wednesday police began an operation to enter the temple to arrest him but delayed it on the request of the monks. The monks warned said it would be an act of religious persecution for police to raid the temple. "If the police raid the temple, it... will be tantamount to a state clampdown on the Jogye Order and on the whole Buddhist movement in South Korea," temple officials said in a statement. As hundreds of police surrounded the temple on Wednesday evening, the executive chief of the temple held a press conference saying the Jogye Order would resolve the issue by noon on Thursday, after which police suspended the raid. On Thursday, Mr Han finally emerged, paid his respects at the main temple, addressed his supporters and the media, and then gave himself up to waiting police. South Korean religious venues, particularly Christian churches, were often used by political activists seeking refuge in the 1980s. There is no law preventing police from raiding such buildings but they have often opted not to. Those at the protest in November had a diverse range of grievances, from President Park Geun-hye's plans to make it easier to sack workers, to a decision to use only one, state-approved history textbook in the nation's schools. The rally, which the government says was illegal, saw clashes between police using pepper spray and water cannon, and protesters, some of whom were armed with metal pipes and sharpened bamboo sticks. The subsequent police crackdown prompted a smaller demonstration on Saturday - 14,000 people, rather than the 60,000 estimated at November's protest - to demand an apology from the president. Ms Park has drawn the ire of labour unions and farmers for planning to make it easier to dismiss workers and to cap the salaries of senior employees. However, many of her labour market policies are more popular with the general public, according to polls. The BBC's Stephen Evans in Seoul says there is an increasingly bitter division between South Korea's conservative government and its left-wing critics, who accuse it of diminishing democracy.

Response:
Police in South Korea have detained a trade union leader who has been taking refuge in a Buddhist Temple in Seoul for almost a month.

========================================================================================================================
Sample 8
------------------------------------------------------------------------------------------------------------------------
Prompt:

In [19]:
TARGET_SAMPLES = 8000

df = pd.DataFrame(rows)

if len(df) > TARGET_SAMPLES:
    df = (
        df.sample(n=TARGET_SAMPLES, random_state=42)
          .reset_index(drop=True)
    )

if os.path.exists(OUTPUT_FILE):
    existing = pd.read_csv(OUTPUT_FILE)

    df = (
        pd.concat([existing, df], ignore_index=True)
          .drop_duplicates(subset=["prompt", "response"])
          .reset_index(drop=True)
    )

df.to_csv(OUTPUT_FILE, index=False)

print(f"Saved {len(df):,} samples to {OUTPUT_FILE}")
print(df.sample(10, random_state=42))

Saved 23,786 samples to writing.csv
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         prompt  \
19085                                                                                                                                                                                                                                                                                                                                                                        Summarize the content below. By . Daily Mail Reporter . PUBLISHED: . 19:17 EST, 25 November 2012 . | . UPDATED: . 03:32 EST, 26 November 2012 . Born when Gladstone was Prime Minister, Thomas the tortoise has survived everything since 1882, even Nazi bombs. But Thomas, now Britain’s oldest resident, hid a secret under its shell for most of those 130 years – being a female. The tortoise was pulled from the rubble of a bomb-hit house in Essex in 1945. But it was only when owner June Le Gallez of Guernsey inherited Thomas in 1978 that a vet found the truth, after 96 years. Identity crisis: Thomas is 130 years old and was only discovered to be a girl after 96 years . ‘People suggested I rename him Tomasina, . but I thought it would be cruel to change it,’ said Mrs Le Gallez, 54, . adding: ‘She isn’t slowing down. People can’t believe how active she . is.’ Mrs Le Gallez, 54, who cares for the reptile at her home on the . Channel Island of Guernsey, added: ‘Thomas is very much part of the . family. I have pictures with her when I was as young as two. 'Because she is so old we thought we would have lost her by now but she is tough. I sometimes wonder if she will outlive me. ‘She’s always been very big for her age. ‘Thomas used to live and run in the garden when she was younger but now we keep her in the house and she bumbles around. ‘She is just a massive part of the family and everyone is very fond of her. ‘She really races around when she wants to. She’s really fast.’ Mrs Le Gallez inherited Thomas from her cousin Grace Hilditch in 1978. Ms Hilditch had been given Thomas in 1922 as a present from her father Harry, who was friends with a reptile keeper at London Zoo. Healthy diet: Could the secret to Thomas's long life be her love of bananas? When they adopted Thomas the keeper informed Harry she was 40 years old putting her birth date at 1882. Thomas lived happily with Ms Hilditch for 56 years at her home in Ilford, Essex, which was bombed in 1945 and a warden managed to rescue her from the rubble. She was given to Mrs Le Gallez and husband Richard after Ms Hilditch had fallen ill and later died. June said: ‘The journey from Essex to Guernsey with Thomas was a rather funny one. ‘Staff on the train asked me if I wanted anything to eat and drink and if Thomas wanted any lettuce leaves.’ Thomas is kept company in the garden by fellow tortoises Gorky and Carstaias, who are both 50 years old, and her favourite food is bananas. The oldest recorded tortoise in Britain was Timmy, a Mediterranean spur-thighed tortoise who was believed to be 160 years old when she died in 2004 at Powderham Castle, Devon. David Alderton, Editor of Practical Reptile Keeping magazine said: ‘Although many people have contacted us about tortoises over 50 years old, some of which they’ve had since childhood, we’ve only heard to date of two individuals who are more than 100 years old.’
20177                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Provide a brief overview of the following news article. By . Claire Bates . PUBLISHED: . 10:02 EST, 3 October 2012 . | . UPDATED: . 10:14 EST, 3 October 2012 . Nearly all of us have experienced the familiar butterflies when it's time for the dreaded trip to the dentist. Now one enterprising dental surgeon from Java, Indonesia, has created a new tool he hopes will put a smile instead of a grimace on his patients' faces. Dr Dhanni Gustiana has created a musical drill to drown out the ominous high-pitch whine of the tool. He hopes it will especially soothe his nervous younger patients. SCROLL DOWN FOR VIDEO . Dr Gustiana (pictured) modified a conventional dental drill, changing the buzzing sound to the music from a MP3 player . Dr Gustiana, 37, from Purworejo, Central Java province, decided to create the new appliance after finding out the drill was what children feared most. He said: 'The children are not afraid of doctor, many of them are afraid of drill. I modified this by putting a toy on the head of the drill and tell them that the toy will clean their teeth.' In 2006, after a year of research, Dr Gustiana created a musical dental drill. He modified a conventional dental drill, changing the buzzing sound to the music from a MP3 player. It also features colourful flashing lights. 'The patient will hear the music louder when they open their mouths compared to when they close their mouths,' said Dr Gustiana. The dental surgeon spent about six million rupiah (£372) to modify the instrument. His patients can even request songs loaded onto the MP3 player. Bringing fun into the dreaded dentist's room? The drill also features flashing lights and toys to distract children . Gustiana also has various figurines made from silicon which can be placed on the drill head. He treats more than 15 patients a day, of whom about half are children. He says some adults also ask him to use the singing drill on them. One young patient, Anavaya Siddartta, appeared to enjoy her dental treatment with the musical mouth implement at Gustiana's surgery. Her mother, Christine Ratnawati, said: 'Very interesting, the children listening to the music and they forget about the drill in their mouth. This is a good idea to overcome fear of dental drill.' Dr Gustiana said with the musical drill, most of his children's patients are not even aware of what he is doing. He presented his creation at the International Dental Congress in Greece in March this year.
20918  Briefly describe the following article. GBR 1, driven by John Jackson, were fifth, 0.11 seconds off a medal, as Russian pilot Alexander Zubkov, 39, finished 0.09 secs clear of Latvia. United States won bronze while Lamin Deen and the GBR 2 crew were 19th. Great Britain finished the Sochi 2014 Games 19th in the medal table, with one gold, one silver and two bronzes. It has been a great race and to only finish 0.11 seconds off the medals is amazing That haul of four medals equals the total they won at the inaugural Games in 1924. Britain surpassed their three-medal Sochi target, thanks to Lizzy Yarnold (skeleton gold), the men's curlers (silver) Jenny Jones (snowboard slopestyle bronze) and the bronze won by the women's curling team on Thursday. Jackson's four-man team of Stuart Benson, Bruce Tasker and Joel Fearon won a historic World Cup silver medal in December and finished second at last month's European Championships. However, they were ranked 12th in the world heading into the Olympics and lay in seventh position after the first two runs on Saturday. They climbed to sixth in the penultimate run on Sunday before finishing in fifth. An analysis of their times from each run showed that they were twice the second quickest sled and were third once - but their opening run, where they were tenth - cost them. "It's hard to think we've come so close to a medal," Jackson told BBC Sport. "Hopefully this will be enough to secure backing [from UK Sport] so we can continue to progress." The 36-year-old pilot, who is also a royal marine sergeant, ruptured his Achilles tendon in July and only reached the Olympics after undergoing pioneering surgery. "For a split second I thought potentially I may not be here [when it happened] but the support I've had from my team-mates since day one has been amazing," said Jackson. "I am ashamed to say that I cried at the end but he had a fantastic run and the amount of speed he had proves how well he was driving. There were just a few guys out there who were a bit better. "I think it's amazing that John's come from where he has been this last year [with the Achilles injury] and to still achieve what he has with fifth in the Olympic Games. I'd be quite afraid of them next year when they're back on the track in the World Cup." Benson added: "We've always had belief in him and he drove superbly. I hope he stays around for another four years because that will mean I'll be here again." Jackson told BBC Sport he plans to continue for "another couple of seasons" but is unlikely to compete through to the 2018 Olympics in Pyeongchang, Korea. GBR 2 pilot Deen, 32, who has been non-committal on his future prior to the Games says he is now determined to carry on in the British programme. "It's been an amazing experience and although all of the runs didn't go as we would have hoped the guys have been fantastic and I want to come back a better pilot in 2018," he told BBC Radio 5 Live. The British bobsleigh team will now face an anxious wait for UK Sport to announce the amount of funding they will receive for the next four-year period. Their four-man target was a top-six finish, which they achieved, but the women were 12th when chasing top-eight. A decision is due to be announced in June.
15335                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Explain the article briefly. The software giant posted a $4.7bn (Â£3.8bn) profit for the three months to September. Chief executive Satya Nadella has focused on building Microsoft's expertise in cloud-based services amid slowing PC sales. Shares rose 6% to $60.73 in after-hours trading. The previous high was $59.97 in December 1999, close to the peak of the dot-com boom, shortly before Steve Ballmer replaced Bill Gates as chief executive. When Mr Nadella succeeded Mr Ballmer in 2014, Microsoft's shares were trading below $37. Investor confidence in Microsoft has been restored by focusing on mobile and cloud computing rather than its traditional products such as the Windows operating system and Office software. Individuals and businesses are increasingly accessing computing services such as servers, databases, software and storage that are provided over the internet ("the cloud"). And Mr Nadella said the changing business environment meant this was paying off. "It's not just the Silicon Valley startups anymore; it is the core enterprise that is also becoming a digital company. And we are well-positioned to serve them," Mr Nadella said. Revenue from Microsoft's Office 365 cloud service increased 8% in the quarter while revenue from its Surface tablet - pitched as a rival to the iPad - rose 38%. And while revenue from its flagship Xbox - Microsoft's games console - fell, the number of people playing online rose to 47 million from 39 million a year.
4347                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Write a concise summary of this article.\n\nThe 26-year-old, who was a free agent after leaving Belgian team Royal Excel Mouscron, has signed a three-year contract with the O's.\nMezague came through the youth ranks with Montpellier in his homeland and moved to play in Belgium in 2014.\nMeanwhile, Barnet winger Luke Gambin has turned down a move to Orient.\nChairman Tony Kleanthous told his club's website that a £100,000 deal had been agreed, but the 23-year-old is out of contract in the summer and wants to play at a higher level than League Two.\nFind all the latest football transfers on our dedicated page.

In [20]:
rows = []

In [21]:
dataset = load_dataset(
    "jhu-clsp/jfleg",
    split="validation"
)

README.md: 0.00B [00:00, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/148k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/141k [00:00<?, ?B/s]

Generating validation split:   0%|          | 0/755 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/748 [00:00<?, ? examples/s]

In [22]:
grammar_prompts = [
    "Correct the grammar in the following sentence.",
    "Fix the grammatical errors.",
    "Rewrite the sentence using proper grammar.",
    "Proofread the following text.",
    "Correct the spelling and grammar mistakes.",
    "Improve the fluency of the sentence.",
    "Rewrite the following sentence naturally.",
    "Edit the sentence for grammatical correctness.",
    "Polish the writing while preserving its meaning.",
    "Improve the readability of the following sentence.",
    "Rewrite the sentence to sound more natural.",
    "Revise the following text for grammar and clarity.",
    "Correct the writing errors without changing the meaning.",
    "Improve the sentence structure.",
    "Make the following sentence grammatically correct.",
    "Rewrite this text using standard English.",
    "Refine the grammar of the following sentence.",
    "Correct any language mistakes in the text.",
    "Edit the sentence for better fluency.",
    "Rewrite the sentence with improved grammar."
]

start = len(rows)

for sample in tqdm(dataset):

    source = clean_text(sample["sentence"])

    for target in sample["corrections"]:

        target = clean_text(target)

        if source == target:
            continue

        prompt = f"{random.choice(grammar_prompts)}\n\n{source}"

        add_sample(prompt, target)

added = len(rows) - start

print(f"Added: {added:,}")

  0%|          | 0/755 [00:00<?, ?it/s]

Added: 2,567

In [23]:
preview = pd.DataFrame(rows)

print(f"Samples: {len(preview):,}")

preview.sample(10, random_state=42)[["prompt", "response"]]

Samples: 2,567

,prompt,response
973,Fix the grammatical errors. In both advertisements is said that these tooth pastes will make your teeth briliant and brighter .,Both advertisements say that the toothpaste will make your teeth brilliant and brighter .
2081,Correct the grammar in the following sentence. an 7unsuspection user cannto tell the entruy has vees tampered with .,An unsuspecting user cannot tell the century has been tampered with .
2017,"Improve the sentence structure. Really successful people gained their fortune by doing somethig new , something that no one else has ever done before , that means that nobody knew how to do it well that was their risk .","Really successful people gained their fortunes by trying something new , something that no one else has ever done before , and taking risks where people were too afraid to ."
952,"Polish the writing while preserving its meaning. For example , they do not like to wait much .","For example , they do not like to wait ."
2531,"Correct the writing errors without changing the meaning. But if one who majors in art also learns something about natural science , he will be lucky to be equipped with the ability to think more logically .","But if one who majors in art also learns something about natural science , he will have the fortune of gaining the ability to think more logically ."
1670,"Rewrite this text using standard English. It is also undeniable that if a man has diversifed knowledge , it would be immediate use .","It is also undeniable that if a man has diversified knowledge , it would be used immediately ."
2122,Rewrite the sentence to sound more natural. I had lots of problem about studying science .,I had lots of problems when studying science .
178,Make the following sentence grammatically correct. In today 's Compuer skill is first important life skill .,"Today , computer skills are the most important life skill ."
1421,"Revise the following text for grammar and clarity. These useful skills that I learned from reality are going to be the greatest gift for my future career , and they can not be found in the text books anyways .","These useful skills that I have learned from real life are going to be the greatest gift to my future career , and they are skills that cannot be found in a textbook ."
2265,Polish the writing while preserving its meaning. They bring us to far places in quite a fast speed without much human physical exertion .,They bring us to far away places quite quickly and without much human physical exertion .

In [24]:
TARGET_SAMPLES = 7000

df = pd.DataFrame(rows)

if len(df) > TARGET_SAMPLES:
    df = (
        df.sample(n=TARGET_SAMPLES, random_state=42)
          .reset_index(drop=True)
    )

if os.path.exists(OUTPUT_FILE):
    existing = pd.read_csv(OUTPUT_FILE)

    df = (
        pd.concat([existing, df], ignore_index=True)
          .drop_duplicates(subset=["prompt", "response"])
          .reset_index(drop=True)
    )

df.to_csv(OUTPUT_FILE, index=False)

rows = []

print(f"Writing Dataset Size: {len(df):,}")

Writing Dataset Size: 26,353

In [28]:
dataset = load_dataset(
    "billsum",
    split="train"
)

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/91.8M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/15.8M [00:00<?, ?B/s]

data/ca_test-00000-of-00001.parquet:   0%|          | 0.00/6.12M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/18949 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3269 [00:00<?, ? examples/s]

Generating ca_test split:   0%|          | 0/1237 [00:00<?, ? examples/s]

In [29]:
billsum_prompts = [
    "Summarize the following bill.",
    "Write a concise summary of the legislation below.",
    "Provide a brief overview of the following bill.",
    "Explain the purpose of this bill.",
    "Summarize the key provisions of the following legislation.",
    "Describe the main objectives of this bill.",
    "Write a short summary of the legislative text.",
    "Summarize the following legal document.",
    "Extract the main points from this bill.",
    "Provide a compact summary of the legislation.",
    "What is the purpose of this bill?",
    "What does the following bill propose?",
    "Summarize the important sections of this bill.",
    "Explain this legislative document briefly.",
    "Write an abstract for the following bill.",
    "Summarize the following government document.",
    "Describe the key ideas presented in this bill.",
    "Write a clear summary of the legal text.",
    "Summarize the content below.",
    "Identify the main purpose of the following legislation."
]

start = len(rows)

for sample in tqdm(dataset):

    document = clean_text(sample["text"])
    summary = clean_text(sample["summary"])

    if len(document.split()) < 50:
        continue

    prompt = f"{random.choice(billsum_prompts)}\n\n{document}"

    add_sample(prompt, summary)

added = len(rows) - start

print(f"Added: {added:,}")

  0%|          | 0/18949 [00:00<?, ?it/s]

Added: 506

In [30]:
preview = pd.DataFrame(rows)

print(f"Samples: {len(preview):,}")

preview.sample(10, random_state=42)[["prompt", "response"]]

Samples: 506

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      prompt  \
173  Describe the main objectives of this bill. SECTION 1. SHORT TITLE. This Act may be cited as the ``Reasserting American Leadership in Space Act'' or the ``REAL Space Act''. SEC. 2. FINDINGS. Congress finds the following: (1) The 109th Congress passed the National Aeronautics and Space Administration Authorization Act of 2005 overwhelmingly, establishing as the National Aeronautics and Space Administration's priority human space flight goal: ``To develop a sustained human presence on the Moon . . . to promote exploration, commerce, science, and United States preeminence in space as a stepping stone for the future exploration of Mars and other destinations.''. (2) The 110th Congress overwhelmingly reaffirmed the vision of returning to the Moon as an integral part of exploring further into our solar system through the passage of the National Aeronautics and Space Administration Authorization Act of 2008, expressing support for ``the broad goals of the space exploration policy of the United States, including the eventual return to and exploration of the Moon and other destinations in the solar system and the important national imperative of independent access to space''. (3) The 111th Congress, in the National Aeronautics and Space Administration Authorization Act of 2010, called for the development of a heavy lift capability of greater than 130 metric tons consisting of the Space Launch System (SLS) and Multi-Purpose Crew Vehicle (MPCV) to pursue exploration, yet fell short on explicitly stating a clear destination. (4) The 112th Congress has reaffirmed this commitment to the development of a heavy lift capability. (5) A sustained human presence on the Moon will allow astronauts and researchers the opportunity to leverage new technologies in addressing the challenges of sustaining life on another celestial body, lessons which are necessary and applicable as we explore further into our solar system, to Mars and beyond. (6) A sustained human presence on the Moon would once again inspire and engage public interest in our space program, motivating young people to excel in the vital subjects of math and science, subjects in which American students lag behind our international competitors. (7) A sustained human presence on the Moon would challenge American industry to continue to develop technologies that not only enhance our exploration programs but can be applied across all disciplines of science. (8) The commercial applications of space technologies have had tens of billions of dollars in economic impact, including products from semiconductors and aircraft controls to scratch- resistant lenses and water purification systems. (9) The healthcare technologies derived from our space program, such as the portable x-ray machine, the MRI, advanced life-saving diagnostics, and the implantable heart aid, have saved and improved countless lives. (10) Space is the world's ultimate high ground, returning to the Moon and reinvigorating our human space flight program is a matter of national security. (11) Technologies developed and sustained by the National Aeronautics and Space Administration's human space flight program, such as liquid and solid rocket propulsion, environmental and life support systems, and communications, navigation, and control systems are important to our military. (12) China and Russia, understanding the economic and strategic importance of human space flight, have declared their intentions of colonizing the Moon and are advancing their lunar exploration plans. (13) It is strategically important that the United States possess and maintain the capabilities of unfettered operation in the space domain, and not cede the space domain to other nations. SEC. 3. MISSION. In accordance with the National Aeronautics and Space Administration Authorization Act of 2005, which established as the National Aeronautics and Space Administration's priority goal: ``To develop a sustained human presence on the Moon . . . to promote exploration, commerce, science, and United States preeminence in space as a stepping stone for the future exploration of Mars and other destinations.'', and in accordance with the National Aeronautics and Space Administration Authorization Act of 2008, which endorsed ``the broad goals of the space exploration policy of the United States, including the eventual return to and exploration of the Moon and other destinations in the solar system and the important national imperative of independent access to space'', the National Aeronautics and Space Administration shall plan to return to the Moon by 2022 and develop a sustained human presence on the Moon, in order to promote exploration, commerce, science, and United States preeminence in space as a stepping stone for the future exploration of Mars and other destinations. The budget requests and expenditures of the National Aeronautics and Space Administration shall be consistent with achieving this goal.
274                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Explain this legislative document briefly. SECTION 1. ENERGY EFFICIENCY RETROFIT PILOT PROGRAM. (a) Definitions.--In this section: (1) Applicant.--The term ``applicant'' means a nonprofit organization that applies for a grant under this section. (2) Energy-efficiency improvement.-- (A) In general.--The term ``energy-efficiency improvement'' means an installed measure (including a product, equipment, system, service, or practice) that results in a reduction in use by a nonprofit organization for energy or fuel supplied from outside the nonprofit building. (B) Inclusions.--The term ``energy-efficiency improvement'' includes an installed measure described in subparagraph (A) involving-- (i) repairing, replacing, or installing-- (I) a roof or lighting system, or component of a roof or lighting system; (II) a window; (III) a door, including a security door; or (IV) a heating, ventilation, or air conditioning system or component of the system (including insulation and wiring and plumbing improvements needed to serve a more efficient system); (ii) a renewable energy generation or heating system, including a solar, photovoltaic, wind, geothermal, or biomass (including wood pellet) system or component of the system; and (iii) any other measure taken to modernize, renovate, or repair a nonprofit building to make the nonprofit building more energy efficient. (3) Nonprofit building.-- (A) In general.--The term ``nonprofit building'' means a building operated and owned by a nonprofit organization. (B) Inclusions.--The term ``nonprofit building'' includes a building described in subparagraph (A) that is-- (i) a hospital; (ii) a youth center; (iii) a school; (iv) a social-welfare program facility; (v) a faith-based organization; and (vi) any other nonresidential and noncommercial structure. (4) Secretary.--The term ``Secretary'' means the Secretary of Energy. (b) Establishment.--Not later than 1 year after the date of enactment of this Act, the Secretary shall establish a pilot program to award grants for the purpose of retrofitting nonprofit buildings with energy-efficiency improvements. (c) Grants.-- (1) In general.--The Secretary may award grants under the program established under subsection (b). (2) Application.--The Secretary may award a grant under this section if an applicant submits to the Secretary an application at such time, in such form, and containing such information as the Secretary may prescribe. (3) Criteria for grant.--In determining whether to award a grant under this section, the Secretary shall apply performance-based criteria, which shall give priority to applications based on-- (A) the energy savings achieved; (B) the cost-effectiveness of the energy-efficiency improvement; (C) an effective plan for evaluation, measurement, and verification of energy savings; (D) the financial need of the applicant; and (E) the percentage of the matching contribution by the applicant. (4) Limitation on individual grant amount.--Each grant awarded under this section shall not exceed-- (A) an amount equal to 50 percent of the energy- efficiency improvement; and (B) $200,000. (5) Cost sharing.-- (A) In general.--A grant awarded under this section shall be subject to a minimum non-Federal cost-sharing requirement of 50 percent. (B) In-kind contributions.--The non-Federal share may be provided in the form of in-kind contributions of materials or services. (d) Authorization of Appropriations.--There is authorized to be appropriated to carry out this section $10,000,000 for each of fiscal years 2016 through 2020, to remain available until expended. (e) Offset.--Section 422(f) of the Energy Independence and Security Act of 2007 (42 U.S.C. 17082(f)) is amended-- (1) in paragraph (3), by striking ``and'' at the end; (2) in paragraph (4), by striking ``2018.'' and inserting ``2015;''; and (3) by adding at the end the following: ``(5) $150,000,000 for fiscal year 2016; and ``(6) $200,000,000 for each of fiscal years 2017 and 2018.''.
491                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Summarize the following bill. SECTION 1. SHORT TITLE. This Act may be cited as the ``Personal Health Investment Today Act of 2015'' or the ``PHIT Act of 2015''. SEC. 2. PURPOSE. The purpose of this Act is to promote health and prevent disease, particularly diseases related to being overweight and obese, by-- (1) encouraging healthier lifestyles; (2) providing financial incentives to ease the financial burden of engaging in healthy behavior; and (3) increasing the ability of individuals and families to participate in physical fitness activities. SEC. 3. CERTAIN AMOUNTS PAID FOR PHYSICAL ACTIVITY, FITNESS, AND EXERCISE TREATED AS AMOUNTS PAID FOR MEDICAL CARE. (a) In General.--Paragraph (1) of section 213(d) of the Internal Revenue Code of 1986 is amended by striking ``or'' at the end of subparagraph (C), by striking the period at the end of subparagraph (D) and inserting ``, or'', and by inserting after subparagraph (D) the following new subparagraph: ``(E) for qualified sports and fitness expenses.''. (b) Qualified Sports and Fitness Expenses.--Subsection (d) of section 213 of the Internal Revenue Code of 1986 is amended by adding at the end the following new paragraph: ``(12) Qualified sports and fitness expenses.-- ``(A) In general.--The term `qualified sports and fitness expenses' means amounts paid exclusively for the sole purpose of participating in a physical activity including-- ``(i) for membership at a fitness facility, ``(ii) for participation or instruction in physical exercise or physical activity, or ``(iii) for equipment used in a program (including a self-directed program) of physical exercise or physical activity. ``(B) Overall dollar limitation.--The aggregate amount treated as qualified sports and fitness expenses with respect to any taxpayer for any taxable year shall not exceed $1,000 ($2,000 in the case of a joint return or a head of household (as defined in section 2(b))). ``(C) Fitness facility.--For purposes of subparagraph (A)(i), the term `fitness facility' means a facility-- ``(i) that provides instruction in a program of physical exercise, offers facilities for the preservation, maintenance, encouragement, or development of physical fitness, or serves as the site of such a program of a State or local government, ``(ii) which is not a private club owned and operated by its members, ``(iii) which does not offer golf, hunting, sailing, or riding facilities, ``(iv) the health or fitness component of which is not incidental to its overall function and purpose, and ``(v) which is fully compliant with the State of jurisdiction and Federal anti- discrimination laws. ``(D) Treatment of exercise videos, etc.--Videos, books, and similar materials shall be treated as described in subparagraph (A)(ii) if the content of such materials constitutes instruction in a program of physical exercise or physical activity. ``(E) Limitations related to sports and fitness equipment.--Amounts paid for equipment described in subparagraph (A)(iii) shall be treated as qualified sports and fitness expenses only-- ``(i) if such equipment is utilized exclusively for participation in fitness, exercise, sport, or other physical activity, ``(ii) in the case of amounts paid for apparel or footwear, if such apparel or footwear is of a type that is necessary for, and is not used for any purpose other than, a specific physical activity, and ``(iii) in the case of amounts paid for any single item of sports equipment (other than exercise equipment), to the extent such amounts do not exceed $250. ``(F) Programs which include components other than physical exercise and physical activity.--Rules similar to the rules of paragraph (6) shall apply in the case of any program that includes physical exercise or physical activity and also other components. For purposes of the preceding sentence, travel and accommodations shall be treated as a separate component.''. (c) Effective Date.--The amendments made by this section shall apply to taxable years beginning after the date of the enactment of this Act.

In [31]:
TARGET_SAMPLES = 5000

df = pd.DataFrame(rows)

if len(df) > TARGET_SAMPLES:
    df = (
        df.sample(n=TARGET_SAMPLES, random_state=42)
          .reset_index(drop=True)
    )

if os.path.exists(OUTPUT_FILE):
    existing = pd.read_csv(OUTPUT_FILE)

    df = (
        pd.concat([existing, df], ignore_index=True)
          .drop_duplicates(subset=["prompt", "response"])
          .reset_index(drop=True)
    )

df.to_csv(OUTPUT_FILE, index=False)

rows = []

print(f"Writing Dataset Size: {len(df):,}")

Writing Dataset Size: 26,859