In [32]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jeromeblanchet/commonsenseqa-nlp-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/jeromeblanchet/commonsenseqa-nlp-dataset

In [33]:
import os
print("Dataset path:", path)

print("\nFiles:")
for file in os.listdir(path):
    print(file)

Dataset path: /kaggle/input/datasets/jeromeblanchet/commonsenseqa-nlp-dataset

Files:
dev_rand_split.jsonl
dev_rand_split_EASY.jsonl
test_rand_split_no_answers.jsonl
train_rand_split_EASY.jsonl
train_rand_split.jsonl

In [34]:
from pprint import pprint
import json
import os

train_file = os.path.join(path, "train_rand_split.jsonl")

with open(train_file, "r", encoding="utf-8") as f:
    sample = json.loads(next(f))

pprint(sample)

{'answerKey': 'A',
 'id': '075e483d21c29a511267ef62bedc0461',
 'question': {'choices': [{'label': 'A', 'text': 'ignore'},
                          {'label': 'B', 'text': 'enforce'},
                          {'label': 'C', 'text': 'authoritarian'},
                          {'label': 'D', 'text': 'yell at'},
                          {'label': 'E', 'text': 'avoid'}],
              'question_concept': 'punishing',
              'stem': 'The sanctions against the school were a punishing blow, '
                      'and they seemed to what the efforts the school had made '
                      'to change?'}}

In [35]:
import json
import os

train_file = os.path.join(path, "train_rand_split.jsonl")

with open(train_file, "r", encoding="utf-8") as f:

    for i, line in enumerate(f):

        sample = json.loads(line)

        question = sample["question"]["stem"]

        answer_key = sample["answerKey"]

        # Convert choices into a dictionary
        choices = {
            choice["label"]: choice["text"]
            for choice in sample["question"]["choices"]
        }

        answer = choices[answer_key]

        print("Question :", question)
        print("Answer   :", answer)
        print("-" * 80)

        if i == 4:   # Show first 5 samples
            break

Question : The sanctions against the school were a punishing blow, and they seemed to what the efforts the school had made to change?
Answer   : ignore
--------------------------------------------------------------------------------
Question : Sammy wanted to go to where the people were.  Where might he go?
Answer   : populated areas
--------------------------------------------------------------------------------
Question : To locate a choker not located in a jewelry box or boutique where would you go?
Answer   : jewelry store
--------------------------------------------------------------------------------
Question : Google Maps and other highway and street GPS services have replaced what?
Answer   : atlas
--------------------------------------------------------------------------------
Question : The fox walked from the city into the forest, what was it looking for?
Answer   : natural habitat
--------------------------------------------------------------------------------

In [36]:
PROMPT_TEMPLATES = [
    "{}",
    "Answer the following question: {}",
    "Provide the best answer: {}",
    "What is the correct answer? {}",
    "Can you answer this? {}"
]

In [37]:
def format_answer(answer):
    answer = answer.strip()

    if not answer.endswith("."):
        answer += "."

    return answer[0].upper() + answer[1:]

In [38]:
RESPONSE_TEMPLATES = [
    "{}.",
    "The answer is {}.",
    "The correct answer is {}.",
    "It is {}.",
    "{} is the correct answer.",
    "Usually {}.",
    "Most commonly {}.",
    "Typically {}.",
    "The best answer is {}.",
    "The most appropriate answer is {}.",
    "The correct choice is {}.",
    "The right answer is {}.",
    "People generally choose {}.",
    "A suitable answer is {}.",
    "The expected answer is {}."
]

In [39]:
import json
import os
import random
import pandas as pd

TARGET_SAMPLES = 15000

def format_answer(answer):
    answer = answer.strip()

    if answer:
        answer = answer[0].upper() + answer[1:]

    template = random.choice(RESPONSE_TEMPLATES)
    response = template.format(answer)

    if not response.endswith("."):
        response += "."

    return response


files = [
    os.path.join(path, "train_rand_split.jsonl"),
    os.path.join(path, "dev_rand_split.jsonl")
]

dataset = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        for line in f:
            sample = json.loads(line)

            question = sample["question"]["stem"].strip()

            choices = {
                c["label"]: c["text"]
                for c in sample["question"]["choices"]
            }

            answer = choices[sample["answerKey"]]

            for prompt_template in PROMPT_TEMPLATES:
                prompt = prompt_template.format(question)
                response = format_answer(answer)

                dataset.append({
                    "prompt": prompt,
                    "response": response
                })

print(f"Generated samples: {len(dataset):,}")

random.shuffle(dataset)

if len(dataset) > TARGET_SAMPLES:
    dataset = dataset[:TARGET_SAMPLES]

print(f"Saving samples: {len(dataset):,}")

df = pd.DataFrame(dataset)

df.to_csv("reasoning.csv", index=False, encoding="utf-8")

print(df.head())

Generated samples: 54,810
Saving samples: 15,000
                                              prompt  \
0  Can you answer this? What is helping likely to...
1  What is the correct answer? Billy set of the c...
2  Answer the following question: You can find ca...
3  The man took paperwork to other people to cons...
4  Food on what kind of transport is normally fre...

                             response
0  The right answer is Good feelings.
1         A suitable answer is Floor.
2                     Usually Casino.
3     The expected answer is Meeting.
4        Most commonly Space shuttle.

In [40]:
!pip -q install datasets transformers sentencepiece tqdm

In [41]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset(
    "open-thoughts/OpenThoughts-114k",
    split="train"
)

print(dataset)
print(dataset[0])

Dataset({
    features: ['system', 'conversations'],
    num_rows: 113957
})

In [42]:
print(dataset.column_names)

for column in dataset.column_names:
    print(f"\n{column}")
    print(dataset[column][0])

['system', 'conversations']

system
Your role as an assistant involves thoroughly exploring questions through a systematic long thinking process before providing the final precise and accurate solutions. This requires engaging in a comprehensive cycle of analysis, summarizing, exploration, reassessment, reflection, backtracing, and iteration to develop well-considered thinking process. Please structure your response into two main sections: Thought and Solution. In the Thought section, detail your reasoning process using the specified format: <|begin_of_thought|> {thought with steps separated with '\n\n'} <|end_of_thought|> Each step should include detailed considerations such as analisying questions, summarizing relevant findings, brainstorming new ideas, verifying the accuracy of the current steps, refining any errors, and revisiting previous steps. In the Solution section, based on various attempts, explorations, and reflections from the Thought section, systematically present the final solution that you deem correct. The solution should remain a logical, accurate, concise expression style and detail necessary step needed to reach the conclusion, formatted as follows: <|begin_of_solution|> {final formatted, precise, and clear solution} <|end_of_solution|> Now, try to solve the following question through the above guidelines:

conversations

In [43]:
sample = dataset[0]

for key, value in sample.items():
    print(f"\n{'='*20} {key} {'='*20}")
    print(value)

==================== system ====================
Your role as an assistant involves thoroughly exploring questions through a systematic long thinking process before providing the final precise and accurate solutions. This requires engaging in a comprehensive cycle of analysis, summarizing, exploration, reassessment, reflection, backtracing, and iteration to develop well-considered thinking process. Please structure your response into two main sections: Thought and Solution. In the Thought section, detail your reasoning process using the specified format: <|begin_of_thought|> {thought with steps separated with '\n\n'} <|end_of_thought|> Each step should include detailed considerations such as analisying questions, summarizing relevant findings, brainstorming new ideas, verifying the accuracy of the current steps, refining any errors, and revisiting previous steps. In the Solution section, based on various attempts, explorations, and reflections from the Thought section, systematically present the final solution that you deem correct. The solution should remain a logical, accurate, concise expression style and detail necessary step needed to reach the conclusion, formatted as follows: <|begin_of_solution|> {final formatted, precise, and clear solution} <|end_of_solution|> Now, try to solve the following question through the above guidelines:

==================== conversations ====================

In [44]:
pairs = []

for sample in dataset:
    conv = sample["conversations"]

    if len(conv) >= 2:
        if conv[0]["from"] == "user" and conv[1]["from"] == "assistant":
            pairs.append({
                "prompt": conv[0]["value"].strip(),
                "response": conv[1]["value"].strip()
            })

print(len(pairs))
print(pairs[0])

113957

In [45]:
pairs = []

for sample in dataset:
    conv = sample["conversations"]

    if len(conv) != 2:
        continue

    if conv[0]["from"] != "user" or conv[1]["from"] != "assistant":
        continue

    prompt = conv[0]["value"].strip()
    response = conv[1]["value"].strip()

    if len(prompt) == 0 or len(response) == 0:
        continue

    if len(response) > 5000:
        continue

    pairs.append({
        "prompt": prompt,
        "response": response
    })

print("Total pairs:", len(pairs))
print()
print("Prompt:\n", pairs[0]["prompt"][:500])
print("\n" + "-"*80 + "\n")
print("Response:\n", pairs[0]["response"][:1000])

Total pairs: 8108

Prompt:
 Generate an executable Python function generated from the given prompt. The function should take stdin as input and print the output. Simply call the function after the definition.Having learned the multiplication table, Takahashi can multiply two integers between 1 and 9 (inclusive) together. He cannot do any other calculation.

Given are two integers A and B.

If Takahashi can calculate A \times B, print the result; if he cannot, print `-1` instead.

Constraints

* 1 \leq A \leq 20
* 1 \leq B

--------------------------------------------------------------------------------

Response:
 <|begin_of_thought|>

Okay, let's see. The problem says that Takahashi can multiply two integers between 1 and 9 inclusive. So if either A or B is outside that range, he can't calculate the product, right? So I need to check if both A and B are in 1 to 9. If yes, then output their product. Otherwise, output -1.

Wait, but the input constraints say that A and B can be up to 20. So the input could be, for example, 10 and 5. Since 10 is not between 1 and 9, even though B is 5, which is acceptable, the whole product can't be calculated. So the condition is that both A and B must be between 1 and 9 inclusive. Otherwise, output -1.

So the steps are:

1. Read A and B from input.
2. Check if both A and B are in the range 1-9.
3. If yes, compute A*B and print it.
4. If no, print -1.

Let me look at the examples to confirm.

First example: 2 and 5. Both are between 1-9. So output 10. Correct.

Second example: 5 and 10. 10 is outside. So output -1. Correct.

Third example: 9 and 9. Both are in r

In [46]:
import re

for pair in pairs:
    pair["response"] = re.sub(
        r"<\|begin_of_thought\|>|<\|end_of_thought\|>|<\|begin_of_solution\|>|<\|end_of_solution\|>",
        "",
        pair["response"],
    ).strip()

print(pairs[0]["response"][:1500])

Okay, let's see. The problem says that Takahashi can multiply two integers between 1 and 9 inclusive. So if either A or B is outside that range, he can't calculate the product, right? So I need to check if both A and B are in 1 to 9. If yes, then output their product. Otherwise, output -1.

Wait, but the input constraints say that A and B can be up to 20. So the input could be, for example, 10 and 5. Since 10 is not between 1 and 9, even though B is 5, which is acceptable, the whole product can't be calculated. So the condition is that both A and B must be between 1 and 9 inclusive. Otherwise, output -1.

So the steps are:

1. Read A and B from input.
2. Check if both A and B are in the range 1-9.
3. If yes, compute A*B and print it.
4. If no, print -1.

Let me look at the examples to confirm.

First example: 2 and 5. Both are between 1-9. So output 10. Correct.

Second example: 5 and 10. 10 is outside. So output -1. Correct.

Third example: 9 and 9. Both are in range. So output 81. Correct.

What about edge cases? Like A=1, B=9. That's allowed. Or A=9, B=9. Wait, that's the third example.

What if one of them is 0? Well, the constraints say A and B are at least 1, so maybe not possible. But according to the constraints, the input can't be 0. So we don't have to handle that.

Another edge case: A=10 and B=9. Then A is 10 which is outside, so output -1.

So the code structure would be:

Read two integers A and B.

If A >=1 and <=9 and same for B, then print product. Else, -1.

In [48]:
import os
import pandas as pd
from tokenizers import Tokenizer

MAX_TOKENS = 1024

tokenizer = Tokenizer.from_file(
    "/kaggle/input/datasets/punitkashyap2007/virgo-tokenizer/virgo_tokenizer.json"
)

filtered_pairs = []

for pair in pairs:
    prompt = str(pair["prompt"]).strip()
    response = str(pair["response"]).strip()

    total_tokens = len(tokenizer.encode(prompt + "\n" + response).ids)

    if total_tokens <= MAX_TOKENS:
        filtered_pairs.append({
            "prompt": prompt,
            "response": response
        })

print(f"Kept: {len(filtered_pairs):,} / {len(pairs):,}")

new_df = pd.DataFrame(filtered_pairs)

if os.path.exists("reasoning.csv"):
    existing_df = pd.read_csv("reasoning.csv")
    combined_df = pd.concat([existing_df, new_df], ignore_index=True)
    combined_df.drop_duplicates(subset=["prompt", "response"], inplace=True)
else:
    combined_df = new_df

combined_df.to_csv("reasoning.csv", index=False, encoding="utf-8")

print(f"Added: {len(new_df):,}")
print(f"Total: {len(combined_df):,}")

Kept: 1,619 / 8,108
Added: 1,619
Total: 23,108

In [49]:
tokenizer = Tokenizer.from_file(
    "/kaggle/input/datasets/punitkashyap2007/virgo-tokenizer/virgo_tokenizer.json"
)

MAX_TOKENS = 1024

In [52]:
dataset = load_dataset(
    "allenai/ai2_arc",
    "ARC-Challenge"
)

train = dataset["train"]

print(train)
print(f"Total training samples: {len(train):,}")

README.md: 0.00B [00:00, ?B/s]

ARC-Challenge/train-00000-of-00001.parqu(…):   0%|          | 0.00/190k [00:00<?, ?B/s]

ARC-Challenge/test-00000-of-00001.parque(…):   0%|          | 0.00/204k [00:00<?, ?B/s]

ARC-Challenge/validation-00000-of-00001.(…):   0%|          | 0.00/55.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1119 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1172 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/299 [00:00<?, ? examples/s]

Dataset({
    features: ['id', 'question', 'choices', 'answerKey'],
    num_rows: 1119
})
Total training samples: 1,119

In [53]:
MAX_TOKENS = 1024

In [54]:
PROMPT_TEMPLATES = [
    "Answer the following multiple-choice question.\n\n{}",
    "Choose the correct answer.\n\n{}",
    "Solve this science reasoning question.\n\n{}",
    "Read the question and determine the correct answer.\n\n{}",
    "Find the best answer for the following question.\n\n{}",
    "Select the correct option.\n\n{}"
]

pairs = []

for sample in train:

    question = sample["question"]

    choices = sample["choices"]

    labels = choices["label"]
    texts = choices["text"]

    options = []
    answer = None

    for label, text in zip(labels, texts):
        options.append(f"{label}. {text}")

        if label == sample["answerKey"]:
            answer = text

    question_text = (
        question.strip()
        + "\n\n"
        + "\n".join(options)
    )

    prompt = random.choice(PROMPT_TEMPLATES).format(question_text)
    response = answer.strip()

    total_tokens = len(
        tokenizer.encode(prompt + "\n" + response).ids
    )

    if total_tokens <= MAX_TOKENS:
        pairs.append({
            "prompt": prompt,
            "response": response
        })

print(f"Generated pairs: {len(pairs):,}")
print(pairs[0])

Generated pairs: 1,119
{'prompt': 'Solve this science reasoning question.\n\nGeorge wants to warm his hands quickly by rubbing them. Which skin surface will produce the most heat?\n\nA. dry palms\nB. wet palms\nC. palms covered with oil\nD. palms covered with lotion', 'response': 'dry palms'}

In [55]:
new_df = pd.DataFrame(pairs)

if os.path.exists("reasoning.csv"):
    existing_df = pd.read_csv("reasoning.csv")

    combined_df = pd.concat(
        [existing_df, new_df],
        ignore_index=True
    )

    combined_df.drop_duplicates(
        subset=["prompt", "response"],
        inplace=True
    )

else:
    combined_df = new_df

combined_df.to_csv(
    "reasoning.csv",
    index=False,
    encoding="utf-8"
)

print(f"Added: {len(new_df):,}")
print(f"Total: {len(combined_df):,}")

Added: 1,119
Total: 24,227

In [56]:
dataset = load_dataset(
    "allenai/winogrande",
    "winogrande_xl"
)

train = dataset["train"]

print(train)
print(f"Total training samples: {len(train):,}")

README.md: 0.00B [00:00, ?B/s]

winogrande_xl/train-00000-of-00001.parqu(…):   0%|          | 0.00/2.06M [00:00<?, ?B/s]

winogrande_xl/test-00000-of-00001.parque(…):   0%|          | 0.00/118k [00:00<?, ?B/s]

winogrande_xl/validation-00000-of-00001.(…):   0%|          | 0.00/85.9k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/40398 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1767 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1267 [00:00<?, ? examples/s]

Dataset({
    features: ['sentence', 'option1', 'option2', 'answer'],
    num_rows: 40398
})
Total training samples: 40,398

In [57]:
PROMPT_TEMPLATES = [
    "Complete the sentence with the most appropriate choice.\n\n{}",
    "Choose the correct word to complete the sentence.\n\n{}",
    "Select the best option for the blank.\n\n{}",
    "Fill in the blank using commonsense reasoning.\n\n{}",
    "Determine the correct completion.\n\n{}",
    "Read the sentence carefully and choose the correct answer.\n\n{}",
    "Which option best completes the sentence?\n\n{}"
]

pairs = []

for sample in train:

    sentence = sample["sentence"].strip()
    option1 = sample["option1"].strip()
    option2 = sample["option2"].strip()

    question = (
        f"{sentence}\n\n"
        f"Option 1: {option1}\n"
        f"Option 2: {option2}"
    )

    prompt = random.choice(PROMPT_TEMPLATES).format(question)

    if sample["answer"] == "1":
        response = option1
    else:
        response = option2

    total_tokens = len(
        tokenizer.encode(prompt + "\n" + response).ids
    )

    if total_tokens <= MAX_TOKENS:
        pairs.append({
            "prompt": prompt,
            "response": response
        })

print(f"Generated pairs: {len(pairs):,}")
print()
print(pairs[0])

Generated pairs: 40,398

{'prompt': "Complete the sentence with the most appropriate choice.\n\nIan volunteered to eat Dennis's menudo after already having a bowl because _ despised eating intestine.\n\nOption 1: Ian\nOption 2: Dennis", 'response': 'Dennis'}

In [62]:
PROMPT_TEMPLATES = [
    "Complete the sentence with the most appropriate choice.\n\n{}",
    "Choose the correct word to complete the sentence.\n\n{}",
    "Select the best option for the blank.\n\n{}",
    "Fill in the blank using commonsense reasoning.\n\n{}",
    "Determine the correct completion.\n\n{}",
    "Read the sentence carefully and choose the correct answer.\n\n{}",
    "Which option best completes the sentence?\n\n{}"
]

RESPONSE_TEMPLATES = [
    "The correct answer is **{}** because it best fits the context.",
    "{} is the correct choice because it completes the sentence logically.",
    "Based on the sentence, the correct answer is {}.",
    "{} best completes the sentence according to the context.",
    "The most appropriate answer is {} because it matches the sentence.",
    "The answer is {} since it is the only option consistent with the context.",
    "{} is correct because it makes the sentence meaningful and coherent."
]

pairs = []

for sample in train:

    sentence = sample["sentence"].strip()
    option1 = sample["option1"].strip()
    option2 = sample["option2"].strip()

    question = (
        f"{sentence}\n\n"
        f"Option 1: {option1}\n"
        f"Option 2: {option2}"
    )

    prompt = random.choice(PROMPT_TEMPLATES).format(question)

    if sample["answer"] == "1":
        correct = option1
    else:
        correct = option2

    response = random.choice(RESPONSE_TEMPLATES).format(correct)

    total_tokens = len(
        tokenizer.encode(prompt + "\n" + response).ids
    )

    if total_tokens <= MAX_TOKENS:
        pairs.append({
            "prompt": prompt,
            "response": response
        })

print(f"Generated pairs: {len(pairs):,}")
print()
print(pairs[0])

Generated pairs: 40,398

{'prompt': "Read the sentence carefully and choose the correct answer.\n\nIan volunteered to eat Dennis's menudo after already having a bowl because _ despised eating intestine.\n\nOption 1: Ian\nOption 2: Dennis", 'response': 'Dennis best completes the sentence according to the context.'}

In [68]:
import pprint
pprint.pp(pairs[10])

{'prompt': 'Choose the correct word to complete the sentence.\n'
           '\n'
           'The treasury workers took the gold bars off of the trolley and '
           'stacked them in the safe until the _ was empty.\n'
           '\n'
           'Option 1: safe\n'
           'Option 2: trolley',
 'response': 'trolley is correct because it makes the sentence meaningful and '
             'coherent.'}

In [69]:
df = pd.read_csv("/kaggle/working/reasoning.csv")
df.shape

(64625, 2)

In [70]:
dataset = load_dataset(
    "AI-MO/NuminaMath-CoT",
    split="train"
)

print(dataset)

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00005.parquet:   0%|          | 0.00/247M [00:00<?, ?B/s]

data/train-00001-of-00005.parquet:   0%|          | 0.00/247M [00:00<?, ?B/s]

data/train-00002-of-00005.parquet:   0%|          | 0.00/247M [00:00<?, ?B/s]

data/train-00003-of-00005.parquet:   0%|          | 0.00/247M [00:00<?, ?B/s]

data/train-00004-of-00005.parquet:   0%|          | 0.00/247M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/166k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/859494 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/100 [00:00<?, ? examples/s]

Dataset({
    features: ['source', 'problem', 'solution', 'messages'],
    num_rows: 859494
})

In [71]:
print(dataset[0]["problem"])
print("=" * 80)
print(dataset[0]["solution"])

Consider the terms of an arithmetic sequence: $-\frac{1}{3}, y+2, 4y, \ldots$. Solve for $y$.
================================================================================
For an arithmetic sequence, the difference between consecutive terms must be equal. Therefore, we can set up the following equations based on the sequence given:
\[ (y + 2) - \left(-\frac{1}{3}\right) = 4y - (y+2) \]

Simplify and solve these equations:
\[ y + 2 + \frac{1}{3} = 4y - y - 2 \]
\[ y + \frac{7}{3} = 3y - 2 \]
\[ \frac{7}{3} + 2 = 3y - y \]
\[ \frac{13}{3} = 2y \]
\[ y = \frac{13}{6} \]

Thus, the value of $y$ that satisfies the given arithmetic sequence is $\boxed{\frac{13}{6}}$.

In [73]:
from tqdm.auto import tqdm

PROMPT_TEMPLATES = [
    "Solve the following mathematics problem.\n\n{}",
    "Find the correct solution.\n\n{}",
    "Solve step by step.\n\n{}",
    "Determine the answer with proper reasoning.\n\n{}",
    "Work through the following problem.\n\n{}",
    "Answer the following mathematics question.\n\n{}",
    "Compute the result and justify each step.\n\n{}"
]

pairs = []

for sample in tqdm(
    dataset,
    total=len(dataset),
    desc="Processing NuminaMath"
):

    problem = sample["problem"].strip()
    solution = sample["solution"].strip()

    prompt = random.choice(PROMPT_TEMPLATES).format(problem)
    response = solution

    total_tokens = len(
        tokenizer.encode(prompt + "\n" + response).ids
    )

    if total_tokens <= MAX_TOKENS:
        pairs.append({
            "prompt": prompt,
            "response": response
        })

print(f"\nGenerated pairs: {len(pairs):,}")

print("\nExample Prompt:\n")
print(pairs[0]["prompt"])

print("\n" + "=" * 80 + "\n")

print("Example Response:\n")
print(pairs[0]["response"])

Processing NuminaMath:   0%|          | 0/859494 [00:00<?, ?it/s]

Generated pairs: 750,906

Example Prompt:

Compute the result and justify each step.

Consider the terms of an arithmetic sequence: $-\frac{1}{3}, y+2, 4y, \ldots$. Solve for $y$.

================================================================================

Example Response:

For an arithmetic sequence, the difference between consecutive terms must be equal. Therefore, we can set up the following equations based on the sequence given:
\[ (y + 2) - \left(-\frac{1}{3}\right) = 4y - (y+2) \]

Simplify and solve these equations:
\[ y + 2 + \frac{1}{3} = 4y - y - 2 \]
\[ y + \frac{7}{3} = 3y - 2 \]
\[ \frac{7}{3} + 2 = 3y - y \]
\[ \frac{13}{3} = 2y \]
\[ y = \frac{13}{6} \]

Thus, the value of $y$ that satisfies the given arithmetic sequence is $\boxed{\frac{13}{6}}$.

In [74]:
dataset.to_pandas()["source"].value_counts()

source
cn_k12            276554
synthetic_math    167874
orca_math         153314
olympiads         150563
synthetic_amc      62108
aops_forum         30192
math                7477
gsm8k               7342
amc_aime            4070
Name: count, dtype: int64

In [76]:
from tqdm.auto import tqdm

df = pd.DataFrame({
    "source": [x["source"] for x in tqdm(dataset, desc="Loading dataset")],
    "problem": [x["problem"] for x in dataset],
    "solution": [x["solution"] for x in dataset],
})

print("Before:", len(df))

df = df.drop_duplicates(subset=["problem"]).reset_index(drop=True)

print("After :", len(df))
print("Removed:", 859494 - len(df))

Loading dataset:   0%|          | 0/859494 [00:00<?, ?it/s]

Before: 859494
After : 816958
Removed: 42536

In [77]:
print(df["source"].value_counts())

source
cn_k12            268870
orca_math         149186
synthetic_math    148700
olympiads         143418
synthetic_amc      61916
aops_forum         30165
math                7351
amc_aime            3778
gsm8k               3574
Name: count, dtype: int64

In [78]:
from collections import defaultdict

stats = defaultdict(list)

for _, row in tqdm(df.iterrows(), total=len(df), desc="Measuring solution length"):
    stats[row["source"]].append(
        len(tokenizer.encode(row["solution"]).ids)
    )

for source in sorted(stats):
    lengths = stats[source]
    print(
        f"{source:16} "
        f"avg={sum(lengths)/len(lengths):7.1f}  "
        f"median={sorted(lengths)[len(lengths)//2]:4d}  "
        f"max={max(lengths):5d}"
    )

Measuring solution length:   0%|          | 0/816958 [00:00<?, ?it/s]

amc_aime         avg=  639.1  median= 615  max= 1535
aops_forum       avg=  986.7  median= 928  max= 4309
cn_k12           avg=  409.5  median= 347  max= 4895
gsm8k            avg=  266.8  median= 253  max=  744
math             avg=  462.9  median= 434  max= 1876
olympiads        avg=  937.4  median= 883  max= 5618
orca_math        avg=  271.9  median= 256  max= 1639
synthetic_amc    avg=  479.1  median= 465  max= 1435
synthetic_math   avg=  331.7  median= 301  max= 2761

In [79]:
TARGETS = {
    "orca_math": 20000,
    "synthetic_math": 10000,
    "cn_k12": 10000,
    "gsm8k": 3574,
    "math": 7351,
    "synthetic_amc": 5000,
    "amc_aime": 2500,
    "olympiads": 5000,
    "aops_forum": 2500,
}

balanced_df = (
    df.groupby("source", group_keys=False)
      .apply(lambda x: x.sample(min(len(x), TARGETS[x.name]), random_state=42))
      .reset_index(drop=True)
)

print(balanced_df["source"].value_counts())
print(f"\nTotal samples: {len(balanced_df):,}")

source
orca_math         20000
synthetic_math    10000
cn_k12            10000
math               7351
olympiads          5000
synthetic_amc      5000
gsm8k              3574
amc_aime           2500
aops_forum         2500
Name: count, dtype: int64

Total samples: 65,925

/tmp/ipykernel_58/3067631010.py:15: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(min(len(x), TARGETS[x.name]), random_state=42))

In [80]:
MAX_SOLUTION_TOKENS = 700

filtered_rows = []

for _, row in tqdm(
    balanced_df.iterrows(),
    total=len(balanced_df),
    desc="Filtering long solutions"
):
    if len(tokenizer.encode(row["solution"]).ids) <= MAX_SOLUTION_TOKENS:
        filtered_rows.append(row)

balanced_df = pd.DataFrame(filtered_rows).reset_index(drop=True)

print(balanced_df["source"].value_counts())
print(f"\nFinal samples: {len(balanced_df):,}")

Filtering long solutions:   0%|          | 0/65925 [00:00<?, ?it/s]

source
orca_math         19917
synthetic_math     9794
cn_k12             8718
math               6460
synthetic_amc      4656
gsm8k              3570
amc_aime           1584
olympiads          1399
aops_forum          588
Name: count, dtype: int64

Final samples: 56,686

In [82]:
from tqdm.auto import tqdm
import random

PROMPT_TEMPLATES = [
    "Solve the following mathematics problem.\n\n{}",
    "Solve this mathematics problem.\n\n{}",
    "Find the correct solution.\n\n{}",
    "Solve step by step.\n\n{}",
    "Determine the answer with proper reasoning.\n\n{}",
    "Work through the following problem.\n\n{}",
    "Answer the following mathematics question.\n\n{}",
    "Compute the result and justify each step.\n\n{}",
    "Find the value(s) that satisfy the problem.\n\n{}",
    "Show the complete mathematical solution.\n\n{}",
    "Carefully solve the following question.\n\n{}",
    "Find the answer using mathematical reasoning.\n\n{}",
    "Provide a complete solution.\n\n{}",
    "Work out the solution with clear reasoning.\n\n{}",
    "Derive the correct answer.\n\n{}",
    "Evaluate the following problem.\n\n{}",
    "Explain how to solve this problem.\n\n{}",
    "Use mathematics to solve the following question.\n\n{}",
    "Determine the correct result.\n\n{}",
    "Solve and explain your reasoning.\n\n{}",
]

pairs = []

for _, row in tqdm(
    balanced_df.iterrows(),
    total=len(balanced_df),
    desc="Creating prompt-response pairs"
):
    problem = str(row["problem"]).strip()
    solution = str(row["solution"]).strip()

    # Skip incomplete samples
    if not problem or not solution:
        continue

    prompt = random.choice(PROMPT_TEMPLATES).format(problem)

    total_tokens = len(
        tokenizer.encode(prompt + "\n" + solution).ids
    )

    if total_tokens <= MAX_TOKENS:
        pairs.append({
            "prompt": prompt,
            "response": solution,
            "source": row["source"]   # Keep for analysis
        })

random.shuffle(pairs)

print(f"Generated pairs: {len(pairs):,}")

print("\nSource distribution:\n")
print(
    pd.DataFrame(pairs)["source"].value_counts()
)

print("\nExample Prompt:\n")
print(pairs[0]["prompt"])

print("\n" + "=" * 100 + "\n")

print("Example Response:\n")
print(pairs[0]["response"])

Creating prompt-response pairs:   0%|          | 0/56686 [00:00<?, ?it/s]

Generated pairs: 56,556

Source distribution:

source
orca_math         19915
synthetic_math     9780
cn_k12             8708
math               6388
synthetic_amc      4649
gsm8k              3570
amc_aime           1573
olympiads          1399
aops_forum          574
Name: count, dtype: int64

Example Prompt:

Find the answer using mathematical reasoning.

In January the families visiting a national park see animals 26 times. In February the families that visit the national park see animals three times as many as were seen there in January. Then in March the animals are shyer and the families who visit the national park see animals half as many times as they were seen in February. How many times total did families see an animal in the first three months of the year?

====================================================================================================

Example Response:

To solve this problem, we follow the information given step by step:

1. In January, animals were seen **26 times**.
2. In February, animals were seen **three times** as many as in January. Therefore, the number of times animals were seen in February is:
   \[
   26 \times 3 = 78 \text{ times}
   \]
3. In March, animals were seen **half as many times** as in February. So, the number of times animals were seen in March is:
   \[
   \frac{78}{2} = 39 \text{ times}
   \]
4. To find the total number of times animals were seen in the first three months of the year, we add the sightings from January, February, and March together:
   \[
   26 + 78 + 39 = 143 \text{ times}
   \]

Therefore, the total number of times families saw an animal in the first three months of the year is $\boxed{143}$ times.

In [83]:
math_df = pd.DataFrame(pairs)

before = len(math_df)

math_df = math_df.drop_duplicates(
    subset=["prompt", "response"]
).reset_index(drop=True)

after = len(math_df)

print(f"Removed duplicates: {before - after:,}")
print(f"Math samples: {after:,}")

Removed duplicates: 0
Math samples: 56,556

In [84]:
reasoning_df = pd.read_csv("/kaggle/working/reasoning.csv")

print(f"Existing samples: {len(reasoning_df):,}")
reasoning_df.head()

Existing samples: 64,625

,prompt,response
0,Can you answer this? What is helping likely to...,The right answer is Good feelings.
1,What is the correct answer? Billy set of the c...,A suitable answer is Floor.
2,Answer the following question: You can find ca...,Usually Casino.
3,The man took paperwork to other people to cons...,The expected answer is Meeting.
4,Food on what kind of transport is normally fre...,Most commonly Space shuttle.

In [85]:
reasoning_df = pd.concat(
    [
        reasoning_df,
        math_df[["prompt", "response"]]
    ],
    ignore_index=True
)

print(f"Total samples after merge: {len(reasoning_df):,}")

Total samples after merge: 121,181

In [86]:
before = len(reasoning_df)

reasoning_df = (
    reasoning_df
    .drop_duplicates(subset=["prompt", "response"])
    .reset_index(drop=True)
)

after = len(reasoning_df)

print(f"Removed duplicates: {before - after:,}")
print(f"Final samples: {after:,}")

Removed duplicates: 0
Final samples: 121,181

In [87]:
reasoning_df = reasoning_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Dataset shuffled.")
print(reasoning_df.head())

Dataset shuffled.
                                              prompt  \
0  Fill in the blank using commonsense reasoning....
1  Complete the sentence with the most appropriat...
2  Work out the solution with clear reasoning.\n\...
3  Generate an executable Python function generat...
4  Use mathematics to solve the following questio...

                                            response
0                                           Benjamin
1                                            fingers
2  Let the income be 5x and the expenditure be 3x...
3  Okay, let's tackle this problem. Hmm, the samp...
4  First, we need to convert the speed of the man...

In [88]:
OUTPUT_PATH = "/kaggle/working/reasoning.csv"

reasoning_df.to_csv(
    OUTPUT_PATH,
    index=False
)

print(f"✅ Saved {len(reasoning_df):,} samples")
print(f"Saved to: {OUTPUT_PATH}")

✅ Saved 121,181 samples
Saved to: /kaggle/working/reasoning.csv

In [89]:
from datasets import load_dataset

dataset = load_dataset(
    "open-r1/OpenR1-Math-220k",
    split="train"
)

print(dataset)

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/20 [00:00<?, ?it/s]

data/train-00000-of-00010.parquet:   0%|          | 0.00/214M [00:00<?, ?B/s]

data/train-00001-of-00010.parquet:   0%|          | 0.00/215M [00:00<?, ?B/s]

data/train-00002-of-00010.parquet:   0%|          | 0.00/215M [00:00<?, ?B/s]

data/train-00003-of-00010.parquet:   0%|          | 0.00/217M [00:00<?, ?B/s]

data/train-00004-of-00010.parquet:   0%|          | 0.00/215M [00:00<?, ?B/s]

data/train-00005-of-00010.parquet:   0%|          | 0.00/214M [00:00<?, ?B/s]

data/train-00006-of-00010.parquet:   0%|          | 0.00/216M [00:00<?, ?B/s]

data/train-00007-of-00010.parquet:   0%|          | 0.00/216M [00:00<?, ?B/s]

data/train-00008-of-00010.parquet:   0%|          | 0.00/214M [00:00<?, ?B/s]

data/train-00009-of-00010.parquet:   0%|          | 0.00/215M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/93733 [00:00<?, ? examples/s]

Dataset({
    features: ['problem', 'solution', 'answer', 'problem_type', 'question_type', 'source', 'uuid', 'is_reasoning_complete', 'generations', 'correctness_math_verify', 'correctness_llama', 'finish_reasons', 'correctness_count', 'messages'],
    num_rows: 93733
})

In [90]:
print(dataset.column_names)

print("\nSample:\n")
print(dataset[0])

['problem', 'solution', 'answer', 'problem_type', 'question_type', 'source', 'uuid', 'is_reasoning_complete', 'generations', 'correctness_math_verify', 'correctness_llama', 'finish_reasons', 'correctness_count', 'messages']

Sample:


In [91]:
from datasets import load_dataset

dataset = load_dataset(
    "open-thoughts/OpenThoughts-114k",
    split="train"
)

print(dataset)

Dataset({
    features: ['system', 'conversations'],
    num_rows: 113957
})

In [92]:
from pprint import pprint

print("System Prompt:\n")
print(dataset[0]["system"])

print("\nConversations:\n")
pprint(dataset[0]["conversations"])

System Prompt:

Your role as an assistant involves thoroughly exploring questions through a systematic long thinking process before providing the final precise and accurate solutions. This requires engaging in a comprehensive cycle of analysis, summarizing, exploration, reassessment, reflection, backtracing, and iteration to develop well-considered thinking process. Please structure your response into two main sections: Thought and Solution. In the Thought section, detail your reasoning process using the specified format: <|begin_of_thought|> {thought with steps separated with '\n\n'} <|end_of_thought|> Each step should include detailed considerations such as analisying questions, summarizing relevant findings, brainstorming new ideas, verifying the accuracy of the current steps, refining any errors, and revisiting previous steps. In the Solution section, based on various attempts, explorations, and reflections from the Thought section, systematically present the final solution that you deem correct. The solution should remain a logical, accurate, concise expression style and detail necessary step needed to reach the conclusion, formatted as follows: <|begin_of_solution|> {final formatted, precise, and clear solution} <|end_of_solution|> Now, try to solve the following question through the above guidelines:

Conversations:

[{'from': 'user',
  'value': 'Generate an executable Python function generated from the given '
           'prompt. The function should take stdin as input and print the '
           'output. Simply call the function after the definition.The Chef '
           'likes to stay in touch with his staff. So, the Chef, the head '
           'server, and the sous-chef all carry two-way transceivers so they '
           'can stay in constant contact. Of course, these transceivers have a '
           'limited range so if two are too far apart, they cannot communicate '
           'directly.\n'
           '\n'
           '\n'
           'The Chef invested in top-of-the-line transceivers which have a few '
           'advanced features. One is that even if two people cannot talk '
           'directly because they are out of range, if there is another '
           'transceiver that is close enough to both, then the two '
           'transceivers can still communicate with each other using the third '
           'transceiver as an intermediate device.\n'
           '\n'
           '\n'
           "There has been a minor emergency in the Chef's restaurant\n"
           'and he needs to communicate with both the head server and the '
           'sous-chef right away. Help the Chef determine if it is possible '
           'for all three people to communicate with each other, even if two '
           'must communicate through the third because they are too far '
           'apart.\n'
           '\n'
           '\n'
           'Input\n'
           '\n'
           'The first line contains a single positive integer T ≤ 100 '
           'indicating the number of test cases to follow. The first line of '
           'each test case contains a positive integer R ≤ 1,000 indicating '
           'that two transceivers can communicate directly without an '
           'intermediate transceiver if they are at most R meters away from '
           'each other. The remaining three lines of the test case describe '
           'the current locations of the Chef, the head server, and the '
           'sous-chef, respectively. Each such line contains two integers X,Y '
           '(at most 10,000 in absolute value) indicating that the respective '
           'person is located at position X,Y.\n'
           '\n'
           '\n'
           'Output\n'
           '\n'
           'For each test case you are to output a single line containing a '
           'single string. If it is possible for all three to communicate then '
           'you should output "yes". Otherwise, you should output "no".\n'
           '\n'
           '\n'
           'To be clear, we say that two transceivers are close enough to '
           'communicate directly if the length of the straight line connecting '
           'their X,Y coordinates is at most R.\n'
           '\n'
           '\n'
           'Example\n'
           '\n'
           'Input:\n'
           '3\n'
           '1\n'
           '0 1\n'
           '0 0\n'
           '1 0\n'
           '2\n'
           '0 1\n'
           '0 0\n'
           '1 0\n'
           '2\n'
           '0 0\n'
           '0 2\n'
           '2 1\n'
           '\n'
           '\n'
           'Output:\n'
           'yes\n'
           'yes\n'
           'no\n'},
 {'from': 'assistant',
  'value': '<|begin_of_thought|>\n'
           '\n'
           "Okay, let's see. I need to solve this problem where three people "
           '(Chef, head server, sous-chef) have transceivers that can '
           "communicate directly if within R meters. If not, but there's a "
           'third person acting as a bridge, then they can still communicate. '
           'The goal is to check if all three can communicate with each other, '
           'possibly through the third.\n'
           '\n'
           'Hmm. So for each test case, given R and three points, determine if '
           'the three form a connected graph where each pair is either '
           'directly connected (distance <= R) or connected via the third.\n'
           '\n'
           "Wait, but how exactly? Let's think. The communication can go "
           'through one intermediary. So all three must be in a chain where '
           'each consecutive pair is within R, or perhaps any two are '
           'connected via a path through the third.\n'
           '\n'
           "Wait, the problem says: if two can't talk directly but there's a "
           'third that is close enough to both, then they can communicate '
           'through that third. So the communication graph must be connected. '
           'But the three people can form a triangle where each is connected '
           "to the others directly, or there's a central node that connects "
           'the other two.\n'
           '\n'
           'So the condition is that all three can communicate with each '
           'other, possibly through one another. So the overall structure must '
           'allow for any two of them to communicate, either directly or via '
           'the third.\n'
           '\n'
           "But how do I model this? Let's think in terms of possible "
           'scenarios where the three can communicate:\n'
           '\n'
           'Case 1: All three are pairwise within R. Then yes.\n'
           '\n'
           'Case 2: Two pairs are within R. For example, Chef to head server '
           'is within R, head server to sous-chef is within R. Then Chef and '
           'sous-chef can communicate through the head server. So all three '
           'can communicate.\n'
           '\n'
           'Case 3: Only one pair is within R, but the third is connected to '
           'both via that pair. Wait, no. For example, Chef and head server '
           'are within R. Chef and sous-chef are not. Head server and '
           'sous-chef are not. Then can the sous-chef communicate with Chef '
           'through the head server? Well, sous-chef would need to be within R '
           "of the head server, but that's not the case here. Wait, no. So if "
           'the head server is connected to Chef (distance <= R), and '
           'sous-chef is connected to the head server (distance <= R), then '
           'yes. But if the sous-chef is connected to neither, but connected '
           'via the Chef and head server? No. Wait, no. Because if the '
           'sous-chef is only connected to the Chef, but the Chef is connected '
           'to the head server, then sous-chef can communicate with the head '
           'server via Chef. But all three would need to form a connected '
           'graph.\n'
           '\n'
           'Wait, perhaps the correct approach is to model the three points as '
           'a graph where edges exist between pairs if their distance is <= R. '
           'Then, check if the graph is connected. If the graph is connected, '
           'then all three can communicate.\n'
           '\n'
           "Yes, that's right. Because if the graph is connected, then all "
           'nodes are reachable via some path. For three nodes, the possible '
           'connected graphs are:\n'
           '\n'
           '- All three nodes connected directly (triangle).\n'
           '- A chain (A connected to B, B connected to C). Then A and C can '
           'communicate via B.\n'
           '\n'
           'So for the problem, we need to check if the three points form a '
           'connected graph in this sense.\n'
           '\n'
           'So the steps for each test case would be:\n'
           '\n'
           '1. Calculate the pairwise distances between all three points.\n'
           '2. For each pair, determine if the distance is <= R. If yes, that '
           'pair is connected.\n'
           '3. Then check if the graph formed by these edges is connected. If '
           "yes, output 'yes', else 'no'.\n"
           '\n'
           'But how to check if the graph is connected with three nodes?\n'
           '\n'
           "Well, for three nodes, the graph is connected if there's at least "
           'two edges such that all three are connected. For example:\n'
           '\n'
           'If there are two edges (A-B and B-C), then connected. If all three '
           'have edges (A-B, B-C, A-C), connected. If two edges (A-B and A-C), '
           'connected.\n'
           '\n'
           "Alternatively, if there's at least two edges and they form a "
           'connected structure. So another approach is to check if all three '
           'are reachable via the edges.\n'
           '\n'
           "But with three nodes, perhaps it's easier to check all possible "
           'conditions.\n'
           '\n'
           'Alternatively, for three nodes, the graph is connected if:\n'
           '\n'
           'Either all three are connected (each pair has an edge), or there '
           'are two edges that connect all three (like a chain), or any two '
           'edges that form a connected graph.\n'
           '\n'
           'Wait, in three nodes, the graph is connected if:\n'
           '\n'
           '- There are at least two edges, and the edges form a path that '
           'connects all three.\n'
           '\n'
           'Alternatively, the connected graph can be checked by seeing if any '
           'one node can reach the other two via the edges.\n'
           '\n'
           "But perhaps for three nodes, it's easier to check all possible "
           'possibilities.\n'
           '\n'
           'So possible scenarios where the graph is connected:\n'
           '\n'
           '1. All three pairs have distance <= R. So all three edges exist. '
           'Then yes.\n'
           '\n'
           '2. Exactly two edges exist, and they form a chain. For example, A '
           'connected to B, B connected to C. Then A can reach C via B. So '
           'yes.\n'
           '\n'
           '3. Exactly one edge exists. Then only two nodes are connected, the '
           'third is isolated. So the graph is disconnected. So no.\n'
           '\n'
           '4. If two edges exist but not forming a chain, like A connected to '
           'B, A connected to C. Then the graph is connected. Because B and C '
           'can communicate through A.\n'
           '\n'
           'So in this case, if any two of the three pairs are connected, and '
           'there exists a third node that connects to at least one of them, '
           'then the graph is connected.\n'
           '\n'
           "Wait, no. Let's think: if A is connected to B and A is connected "
           'to C, then B can reach C through A. So the graph is connected.\n'
           '\n'
           'So for three nodes, the graph is connected if the number of edges '
           'is >=2, and the edges are such that all three are connected. Which '
           "for three nodes, if there are two edges, then it's possible to "
           'have a connected graph.\n'
           '\n'
           'So the possible conditions for the graph to be connected are:\n'
           '\n'
           '- There are at least two edges, and all three nodes are connected '
           'via those edges.\n'
           '\n'
           'Which can be checked by:\n'
           '\n'
           'Either:\n'
           '\n'
           '- All three nodes are connected via their edges (i.e., the edges '
           'form a triangle or a chain).\n'
           '\n'
           'Alternatively, for three nodes, the graph is connected if there '
           'exists a path between every pair of nodes. But with three nodes, '
           "that's possible if the graph is a triangle, a chain, or any two "
           'edges.\n'
           '\n'
           'Wait, perhaps the easiest way is to check if all three nodes are '
           'in the same connected component.\n'
           '\n'
           'How to compute that for three nodes?\n'
           '\n'
           "Well, let's see. For three nodes, there are three possible pairs: "
           'AB, BC, CA.\n'
           '\n'
           'We can represent the edges as a graph, then check if all three '
           'nodes are reachable from each other.\n'
           '\n'
           'But for three nodes, the connectedness can be determined by '
           'checking if the union of the edges connects all three.\n'
           '\n'
           "But maybe it's easier to consider the possible cases:\n"
           '\n'
           'Case 1: All three pairs are within R. Then connected.\n'
           '\n'
           'Case 2: Exactly two pairs are within R. Then check if the two '
           'edges form a connected graph.\n'
           '\n'
           'For example, if AB and BC are connected: then the graph is '
           'connected.\n'
           '\n'
           'If AB and AC are connected: then the graph is connected (since B '
           'and C can communicate via A).\n'
           '\n'
           'If AB and CA are connected: same as above.\n'
           '\n'
           'Case 3: Exactly one pair is within R. Then the third node is '
           'disconnected, so no.\n'
           '\n'
           'Case 4: None of the pairs are within R. Then no.\n'
           '\n'
           'So for the code, perhaps the steps are:\n'
           '\n'
           'For each test case:\n'
           '\n'
           '1. Read R.\n'
           '\n'
           '2. Read the three points (A, B, C).\n'
           '\n'
           '3. Compute the pairwise distances between A-B, B-C, C-A.\n'
           '\n'
           '4. For each pair, determine if the distance is <= R. So check AB '
           '<= R, BC <= R, CA <= R.\n'
           '\n'
           '5. Now, check if the three nodes form a connected graph.\n'
           '\n'
           'The connected graph is possible if:\n'
           '\n'
           'Either:\n'
           '\n'
           '- All three pairs are connected (AB, BC, CA all <= R). Then yes.\n'
           '\n'
           'OR\n'
           '\n'
           '- Any two pairs are connected, and they share a common node (so '
           'forming a triangle or a chain). For example, AB and BC connected '
           '(sharing B), AB and AC connected (sharing A), etc.\n'
           '\n'
           'OR\n'
           '\n'
           '- All three can communicate through a central node. For example, '
           'AB and AC are connected (A is the central node), so B and C can '
           'communicate via A. So in this case, the graph is connected.\n'
           '\n'
           'Alternatively, if two pairs are connected and those two pairs '
           'share a node (so the central node), then the graph is connected.\n'
           '\n'
           'So for two edges:\n'
           '\n'
           'If two edges share a common node (like AB and AC), then '
           'connected.\n'
           '\n'
           'If the two edges are AB and BC, then connected (chain).\n'
           '\n'
           "But if two edges are AB and CA, then it's possible. Wait, AB is "
           'between A and B. CA is between C and A. So A is connected to both '
           'B and C. So B and C can communicate via A. So yes.\n'
           '\n'
           'So any two edges in the three-node graph will form a connected '
           'graph, because with three nodes, two edges must share at least one '
           'node (since there are three possible edges). Wait, no. For '
           'example, AB and BC: two edges, share B. AB and AC: two edges, '
           'share A. AB and CA: AB is A-B, CA is C-A. So A is connected to B '
           'and C. So all three are connected.\n'
           '\n'
           'But what if two edges are AB and CD (but CD is not part of our '
           'three nodes). Wait, no, the three nodes are A, B, C. So any two '
           'edges must be between pairs of these three.\n'
           '\n'
           'So, in three nodes, any two edges will form a connected graph. '
           "Because in three nodes, two edges can't form two separate edges "
           'that are not connected. Let me think: for example, if the edges '
           'are AB and BC: connected. If edges are AB and AC: connected. What '
           'if edges are AB and CD? Not possible. So in three nodes, two edges '
           'will always form a connected graph. Because the two edges have to '
           'connect two pairs, but given that there are three nodes, two edges '
           'must form a chain or a fork.\n'
           '\n'
           'Wait, three nodes, two edges. The possible combinations are:\n'
           '\n'
           '- AB and BC: forms a chain A-B-C. Connected.\n'
           '\n'
           '- AB and AC: forms a fork (A connected to B and C). B and C can '
           'communicate via A. Connected.\n'
           '\n'
           '- AB and CD: but CD is not a pair of the three nodes. So no, '
           "that's not possible.\n"
           '\n'
           'So yes, for three nodes, if there are two edges, the graph is '
           'connected. So the graph is connected if there are two or three '
           'edges.\n'
           '\n'
           'Wait, what if there are two edges between AB and BC: yes, '
           'connected. If two edges between AB and AC: connected. If two edges '
           'between AB and BC: connected. So yes, any two edges in three nodes '
           'will form a connected graph.\n'
           '\n'
           'So the condition is:\n'
           '\n'
           'If the number of edges (each edge is a pair with distance <= R) is '
           '>= 2, then the graph is connected.\n'
           '\n'
           'OR\n'
           '\n'
           'If the graph has two edges, then connected.\n'
           '\n'
           'Wait, but what about three nodes with two edges: AB and BC. So A '
           'is connected to B, B connected to C. Then the graph is connected. '
           'So yes.\n'
           '\n'
           "If two edges are AB and CD (but that's not possible here). So in "
           'our problem, the three nodes are A, B, C. So any two edges must be '
           'between two of these three.\n'
           '\n'
           'So, the conclusion is that for three nodes, the graph is connected '
           'if:\n'
           '\n'
           'The number of edges (edges where distance <= R) is >= 2.\n'
           '\n'
           'Wait, no. Wait, if two edges are AB and BC, then yes. If two edges '
           'are AB and AC, then yes. But what if two edges are AB and CD (but '
           'CD is not part of the nodes). So for our problem, since the nodes '
           'are A, B, C, the edges can only be AB, BC, CA.\n'
           '\n'

In [93]:
from collections import Counter

Counter(len(x) for x in dataset["conversations"])

Counter({2: 113957})

In [94]:
import re
import pandas as pd
from tqdm.auto import tqdm

SOLUTION_RE = re.compile(
    r"<\|begin_of_solution\|>\s*(.*?)\s*<\|end_of_solution\|>",
    flags=re.DOTALL
)

rows = []

for sample in tqdm(dataset):
    prompt = sample["conversations"][0]["value"].strip()
    assistant = sample["conversations"][1]["value"]

    m = SOLUTION_RE.search(assistant)
    if not m:
        continue

    response = m.group(1).strip()

    if len(prompt) < 10 or len(response) < 10:
        continue

    rows.append({
        "prompt": prompt,
        "response": response
    })

df = pd.DataFrame(rows)

print("Extracted:", len(df))
display(df.head())

  0%|          | 0/113957 [00:00<?, ?it/s]

Extracted: 113946

,prompt,response
0,Generate an executable Python function generat...,"To solve this problem, we need to determine if..."
1,Generate an executable Python function generat...,"To solve this problem, we need to compute the ..."
2,Generate an executable Python function generat...,"To solve this problem, we need to determine th..."
3,Generate an executable Python function generat...,"To solve this problem, we need to determine if..."
4,Generate an executable Python function generat...,"To solve this problem, we need to determine if..."

In [97]:
from tqdm.auto import tqdm

MAX_TOKENS = 1024

filtered_rows = []

for row in tqdm(df.itertuples(index=False), total=len(df)):
    text = (
        "<bos>\n"
        + row.prompt
        + "\n\n"
        + row.response
        + "\n<eos>"
    )

    n_tokens = len(tokenizer.encode(text).ids)

    if n_tokens <= MAX_TOKENS:
        filtered_rows.append({
            "prompt": row.prompt,
            "response": row.response
        })

filtered_df = pd.DataFrame(filtered_rows)

print(f"Before: {len(df):,}")
print(f"After : {len(filtered_df):,}")
print(f"Removed: {len(df)-len(filtered_df):,}")

  0%|          | 0/113946 [00:00<?, ?it/s]

Before: 113,946
After : 87,628
Removed: 26,318

In [98]:
import random

random.seed(42)

for i in random.sample(range(len(filtered_df)), 100):
    print("=" * 100)
    print(filtered_df.iloc[i]["prompt"][:400])
    print()

====================================================================================================
"How can understanding the life cycle and transmission of zoonotic parasites contribute to the prevention and control of zoonotic diseases?"

====================================================================================================
Return your final response within \boxed{}. Given a cubic polynomial \( p(x) = a x^{3} + b x^{2} + c x + d \) with integer coefficients \( a, b, c, d \), and knowing that \( p(1) = 2015 \) and \( p(2) = 2017 \), prove that the equation \( p(x) = 2016 \) has no integer roots.

====================================================================================================
Generate an executable Python function generated from the given prompt. The function should take stdin as input and print the output. Simply call the function after the definition.We have N voting papers. The i-th vote (1 \leq i \leq N) has the string S_i written on it.
Print all strings that are written on the most number of votes, in lexicographical order.

-----Constraints-----
 - 1 \leq N \leq

====================================================================================================
Return your final response within \boxed{}. By a tropical polynomial we mean a function of the form
$$
p(x) = a_n \odot x^n \oplus a_{n-1} \odot x^{n-1} \oplus \cdots \oplus a_1 \odot x \oplus a_0,
$$
where exponentiation is as defined in the previous problem.
Let \( p \) be a tropical polynomial. Prove that
$$
p\left(\frac{x+y}{2}\right) \geq \frac{p(x)+p(y)}{2}
$$
for all \( x, y \in \mathbb{R}

====================================================================================================
Return your final response within \boxed{}. Comparison of fractions. Let \( x \) and \( y \) be positive numbers. Which of the fractions is larger:

$$
\frac{x^{2}+y^{2}}{x+y} \quad \text{or} \quad \frac{x^{2}-y^{2}}{x-y} ?
$$

====================================================================================================
Return your final response within \boxed{}. If three non-consecutive vertices of a hexagon lie on a straight line, then the lines connecting the midpoints of the opposite sides of the hexagon intersect at a single point. The vertices of the hexagon may or may not lie in the same plane.

====================================================================================================
Return your final response within \boxed{}. Determine the natural integers $(a, b)$ greater than or equal to 3 such that: $ab^{2} + b + 7 \mid a^{2}b + a + b$.

====================================================================================================
Return your final response within \boxed{}. In an $8 \times 10$ table (8 rows, 10 columns), some cells are black, while the rest are white. In each white cell, the total number of black cells in the same row is written. Nothing is written in the black cells. What is the maximum possible value that the sum of the numbers in the entire table can have?

====================================================================================================
Return your final response within \boxed{}. An ellipse is drawn with major and minor axes of lengths 10 and 8 respectively.  Using one focus as a center, a circle is drawn that is tangent to the ellipse, with no part of the circle being outside the ellipse.  Compute the radius of the circle.

====================================================================================================
Return your final response within \boxed{}. Peter the penguin likes catching fish. On Monday, he realised that if he had caught three times as many fish as he actually did, he would have had 24 more fish. How many fish did Peter catch?

====================================================================================================
Return your final response within \boxed{}. A sequence of real numbers  $\{a_n\}_{n = 1}^\infty (n=1,2,...)$  has the following property:
\begin{align*}
6a_n+5a_{n-2}=20+11a_{n-1}\  (\text{for }n\geq3).
\end{align*}
The first two elements are  $a_1=0, a_2=1$ . Find the integer closest to  $a_{2011}$ .

====================================================================================================
Return your final response within \boxed{}. Suppose \( x, y, z \) are three distinct natural numbers arranged in ascending order, and their reciprocals sum up to a natural number. Find these three natural numbers \( x, y, z \).

====================================================================================================
Generate an executable Python function generated from the given prompt. The function should take stdin as input and print the output. Simply call the function after the definition.Pal like board games. One day Shark shows him a new board game.
This is different from other board games .It follows some rules .

It consists of two characters  "." and "#". (Without quotes).

No two adjacent characters

====================================================================================================
Generate an executable Python function generated from the given prompt. The function should take stdin as input and print the output. Simply call the function after the definition.Alice wrote an exam containing N true or false questions (i.e. questions whose answer is either true or false). Each question is worth 1 mark and there is no negative marking in the examination. Alice scored K marks out

====================================================================================================
Return your final response within \boxed{}. Calculate the result of the expression \(201 \times 5 + 1220 - 2 \times 3 \times 5 \times 7\).

====================================================================================================
Return your final response within \boxed{}. Prove that if a necessary and sufficient criterion for divisibility, expressed through the properties of the digits of a number, does not depend on the order of the digits, then this is a criterion for divisibility by 3 or 9.

====================================================================================================
Return your final response within \boxed{}. The base of a hexagonal prism is a regular hexagon, and the side edges are perpendicular to the base. It is known that all the vertices of the hexagonal prism lie on the same spherical surface, and the volume of the hexagonal prism is \(\frac{9}{8}\). The perimeter of the base is 3. Calculate the volume of the sphere.

====================================================================================================
Return your final response within \boxed{}. Let \( M_n \) be the least common multiple (LCM) of the integers \( 1, 2, \cdots, n \) (e.g., \( M_1 = 1 \), \( M_2 = 2 \), \( M_3 = 6 \), \( M_4 = 12 \), \( M_5 = 60 \), \( M_6 = 60 \)). For which positive integers \( n \) does \( M_{n-1} = M_n \) hold? Prove your conclusion.

====================================================================================================
Return your final response within \boxed{}. Find the sum of all positive integers  $n$  where the mean and median of  $\{20, 42, 69, n\}$  are both integers.

*Proposed by bissue*

====================================================================================================
Generate an executable Python function generated from the given prompt. The function should take stdin as input and print the output. Simply call the function after the definition.Your task is to calculate sum  of primes present as digits of given number N.
Example 1:
Input: 333
Output: 9
Explaination: 3 is a prime number. It
is present 3 times. So 3+3+3 = 9.
Example 2:
Input: 686
Output: 0
Expla

====================================================================================================
Return your final response within \boxed{}. Suppose that the measurement of time during the day is converted to the metric system so that each day has $10$ metric hours, and each metric hour has $100$ metric minutes. Digital clocks would then be produced that would read $\text{9:99}$ just before midnight, $\text{0:00}$ at midnight, $\text{1:25}$ at the former $\text{3:00}$ AM, and $\text{7:50}$ at

====================================================================================================
Return your final response within \boxed{}. Compute the limit of the numerical sequence:

$$
\lim _{n \rightarrow \infty}\left(\frac{n^{3}+n+1}{n^{3}+2}\right)^{2 n^{2}}
$$

====================================================================================================
A triangular loop of wire with sides of length 20 cm, 10 cm, and 15 cm carries a current of 2.5 A. Calculate the magnitude and direction of the magnetic field at the center of the loop.

====================================================================================================
Return your final response within \boxed{}. What is the number of square meters in the area of a circle with diameter 4 meters? Express your answer in terms of $\pi$.

====================================================================================================
Return your final response within \boxed{}.
Márcio starts with a natural number and replaces it with the sum of its digits, repeating the process until he finally gets a single-digit number. For example, Márcio replaces 1784102 with 23, and then with 8. He also applies this process to lists of $N$ natural numbers, replacing each number in the list with the sum of its digits, continuing the proces

====================================================================================================
Return your final response within \boxed{}. A tank has a base area of $6 \mathrm{~m}^{2}$ and the depth of water in it is 75 cm.

====================================================================================================
Return your final response within \boxed{}. Given the function $f(x) = \log_a\left(\frac{1}{2} a x^{2} - x + \frac{1}{2}\right)$ is always positive on the interval $[2, 3]$, determine the range of the real number $a$.

====================================================================================================
Return your final response within \boxed{}. An unlimited supply of 8-cent and 15-cent stamps is available. Some amounts of postage cannot be made up exactly, e.g., 7 cents, 29 cents. What is the largest unattainable amount, i.e., the amount, say  $n$ , of postage which is unattainable while all amounts larger than  $n$  are attainable? (Justify your answer.)

====================================================================================================
Return your final response within \boxed{}. Does there exist a prime number whose decimal representation is of the form \(3811 \ldots 11\) (that is, consisting of the digits 3 and 8 in that order followed by one or more digits 1)?

====================================================================================================
Generate an executable Python function generated from the given prompt. The function should take stdin as input and print the output. Simply call the function after the definition.A number can be called v-number if the sum of the lower half of the array is equal to the sum of the upper half of the array.

EXAMPLE:

if num = 1221

sum of lower half = 3

sum of upper half = 3

then it can be called

====================================================================================================
Return your final response within \boxed{}. Let \( \triangle ABC \) have an inscribed circle \( \Gamma \). This inscribed circle is tangent to sides \( AC, BC, \) and \( AB \) at points \( Y, X, \) and \( Z \), respectively. Let \( \gamma_A \) be the A-excircle tangent to sides \( AC, BC, \) and \( AB \) at points \( K_C, T, \) and \( K_B \), respectively. Show that \( BK_A = CX \).

====================================================================================================
Return your final response within \boxed{}. Compute the limit of the numerical sequence:

$$\lim _{n \rightarrow \infty} \frac{2-5+4-7+\ldots+2 n-(2 n+3)}{n+3}$$

====================================================================================================
Return your final response within \boxed{}. Solve the following equation over the set of integer pairs:

\[ x^{2}-3y^{2}+2xy-2x-10y+20=0 \]

====================================================================================================
Return your final response within \boxed{}. Nine nonnegative numbers have an average of 10. What is the greatest possible value for their median?

====================================================================================================
Return your final response within \boxed{}. Each of the quadratic polynomials \( P(x) \), \( Q(x) \), and \( P(x) + Q(x) \) with real coefficients has a repeated root. Is it necessarily true that all these roots coincide?

====================================================================================================
Return your final response within \boxed{}. Solve the system of equations:
\[
\left\{
\begin{array}{l}
a\left(b^{2}+c\right)=c(c+a b), \\
b\left(c^{2}+a\right)=a(a+b c), \\
c\left(a^{2}+b\right)=b(b+c a).
\end{array}
\right.
\]
(Czech and Slovak Mathematical Olympiad, 64th edition)

====================================================================================================
Return your final response within \boxed{}. The sequence $\{F_n\}$ is defined as follows: $F_1 = 1$, $F_2 = 2$, and $F_{n+2} = F_{n+1} + F_n$ for $n = 1, 2, 3, \ldots$. Prove that for any natural number $n$, $\sqrt[n]{F_{n+1}} \geq 1 + \frac{1}{\sqrt[n]{F_n}}$.

====================================================================================================
Return your final response within \boxed{}. A small cart with a jet engine is positioned on rails. The rails are laid out in the shape of a circle with radius \( R = 5 \) meters. The cart starts from rest, and the jet force has a constant value. What is the maximum speed the cart can reach after completing one full circle, given that its acceleration during this time should not exceed \( a = 1 \,

====================================================================================================
Return your final response within \boxed{}. Find the number of triples of sets \((A, B, C)\) such that:
(a) \(A, B, C \subseteq \{1, 2, 3, \ldots, 8\}\).
(b) \(|A \cap B| = |B \cap C| = |C \cap A| = 2\).
(c) \(|A| = |B| = |C| = 4\).

Here, \(|S|\) denotes the number of elements in the set \(S\).

====================================================================================================
Return your final response within \boxed{}. In a dark storage room, there are shoes of the same size: 12 pairs of black shoes and 12 pairs of brown shoes. What is the minimum number of shoes one needs to take to ensure that there is at least one matching pair (one left shoe and one right shoe) of the same color, given that in the dark, it is impossible to distinguish not only the color of the shoe

====================================================================================================
Return your final response within \boxed{}. Given point $P$ within $\angle A$, draw a line through $P$ that intersects the two sides of $\angle A$ at points $B$ and $C$ respectively. How should the line be drawn through $P$ to minimize the product $BP \cdot PC$?

====================================================================================================
Return your final response within \boxed{}. Let \( a \) be a nonzero real number. In the binomial expansion of \( (ax + 1)^5 \), the coefficient of the \( x^4 \) term is equal to the coefficient of the \( x^3 \) term. Find the value of \( a \).

====================================================================================================
Return your final response within \boxed{}. Two identical smaller cubes are stacked next to a larger cube. Each of the two smaller cubes has a volume of 8. The combined height of the smaller cubes equals the height of the larger cube. What is the volume of the larger cube?
(A) 16
(B) 32
(C) 125
(D) 48
(E) 64

====================================================================================================
Return your final response within \boxed{}. Given the equilateral triangle  $ABC$ . It is known that the radius of the inscribed circle is in this triangle is equal to  $1$ . The rectangle  $ABDE$  is such that point  $C$  belongs to its side  $DE$ . Find the radius of the circle circumscribed around the rectangle  $ABDE$ .

====================================================================================================
Return your final response within \boxed{}. If the sum of two integers is an even number, then their difference is also an even number; if the sum is an odd number, then their difference is also odd. Why?

====================================================================================================
Return your final response within \boxed{}. Write digits in place of the letters in the equation

\[ \overline{abc}^2 = \overline{adeff} \]

to make it correct. (The overline indicates that the letters represent the digits of a number in the decimal system. Identical letters represent identical digits, and identical digits are labeled with the same letters.)

====================================================================================================
Return your final response within \boxed{}. For the integers \( a \) and \( b \), the following equality holds:

\[ a = a^2 + b^2 - 8b - 2ab + 16 \]

Prove that \( a \) is a perfect square.

====================================================================================================
Return your final response within \boxed{}. Seven people arrive to dinner, but the circular table only seats six.  If two seatings such that one is a rotation of the other are considered the same, then in how many different ways can we choose six people and seat them at the table?

====================================================================================================
Return your final response within \boxed{}. Calculate the limit of the function:

$$
\lim _{x \rightarrow 0} \sqrt{4 \cos 3 x+x \cdot \operatorname{arctg}\left(\frac{1}{x}\right)} $$

====================================================================================================
Return your final response within \boxed{}. Given \( x, y, z \in \mathbf{R}^{+} \) and \( x + y + z = 1 \), find the maximum value of the function \( f(x, y, z) = x y^2 z^3 \).

====================================================================================================
Return your final response within \boxed{}. Prove that \( e^{\pi i} = -1 \) and \( e^{2 \pi i} = 1 \).

====================================================================================================
Return your final response within \boxed{}. The function $f$ is not defined for $x = 0,$ but for all non-zero real numbers $x,$
\[f(x) + 2f \left( \frac{1}{x} \right) = 3x.\]Find the real solutions to $f(x) = f(-x).$  Enter the real solutions, separated by commas.

====================================================================================================
Return your final response within \boxed{}. Find all functions \( f: \mathbb{R} \rightarrow \mathbb{R} \) that satisfy the conditions \( f(1+xy) - f(x+y) = f(x) f(y) \) for all \( x, y \in \mathbb{R} \) and \( f(-1) \neq 0 \).

====================================================================================================

In [99]:
import pandas as pd

existing_df = pd.read_csv("/kaggle/working/reasoning.csv")

print("Existing :", len(existing_df))
print("OpenThoughts:", len(filtered_df))

merged_df = pd.concat(
    [existing_df, filtered_df],
    ignore_index=True
)

merged_df = (
    merged_df
    .drop_duplicates(subset=["prompt", "response"])
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

print("Final:", len(merged_df))

merged_df.to_csv(
    "/kaggle/working/reasoning.csv",
    index=False
)

print("Saved to /kaggle/working/reasoning.csv")

Existing : 121181
OpenThoughts: 87628
Final: 208809
Saved to /kaggle/working/reasoning.csv